#!/bin/sh
# GENERATED by tools/i18n-extract.sh — DO NOT EDIT, DO NOT SHIP.
#
# This file is never installed and never run. It exists so that xgettext
# can see the strings that live in Dagric's DATA files — the .look and
# .style drop-ins and the wallpaper packs — which reach the owner through
# dg_tr() at runtime, i.e. through a variable that xgettext cannot follow.
#
# Regenerate with:  sh tools/i18n-extract.sh

# TRANSLATORS: the setup wizard's own buttons, headings and step names.
# This is the first screen a new owner sees. Keep button labels short;
# they sit in fixed-width buttons beside each other.
gettext "Set Up Dagric"
gettext "Every step can be skipped, and you can change all of it later."
gettext "I'll do this later"
gettext "Close setup. Anything already applied stays, and you can run this again from the Dagric Hub"
gettext "Undo my changes"
gettext "Put the colours, wallpaper, text size and taskbar back the way they were when setup opened"
gettext "PRO EDITION"
gettext "Pro edition"
gettext "Live trial — anything you set here lasts until you shut down."
gettext "Back"
gettext "Go back to the previous step"
gettext "Next"
gettext "Go to the next step"
gettext "Finish"
gettext "Close setup and start using Dagric"
gettext "Skip this step"
gettext "Leave this setting alone and go to the next step"
gettext "Let's go"
gettext "Welcome"
gettext "How it looks"
gettext "Text size"
gettext "The taskbar"
gettext "Your files"
gettext "You're ready"
gettext "Step %1"
gettext "Step %1 of %2"
gettext "current step"
gettext "done"
gettext "not done yet"
gettext "Welcome to %1."
gettext "Let's make it yours. A few minutes now — the colours, the wallpaper, how big the text is, where the taskbar sits, and your files from Windows — and then it's out of your way."
gettext "Let's make it yours. A few minutes now — the colours, the wallpaper, how big the text is, where the taskbar sits — and then it's out of your way."
gettext "Pick a look."
gettext "Click anything — the desktop behind this window changes as you go."
gettext "Theme"
gettext "Light"
gettext "Dark"
gettext "Light theme"
gettext "A bright desktop. Shows a small picture of what it looks like."
gettext "Dark theme"
gettext "A dark desktop, easier on the eyes at night."
gettext "Light theme applied."
gettext "Dark theme applied."
gettext "Highlight colour"
gettext "%1 highlight colour applied."
gettext "Wallpaper"
gettext "Wallpaper %1 of %2"
gettext "Arrow keys to move between wallpapers, Space to apply one"
gettext "%1 wallpaper applied."
gettext "Want your own picture? Right-click the desktop and choose Configure Desktop."
gettext "Is the text the right size?"
gettext "Dagric guessed from your screen. Open Display Settings if it guessed wrong."
gettext "Dagric guessed from your screen. A change here takes effect the next time you sign in."
gettext "Dagric guessed from your screen. Pick another size and it changes right away."
gettext "Open Display Settings"
gettext "Opens the full display and text size settings in a separate window"
gettext "Normal"
gettext "Standard size"
gettext "Bigger"
gettext "Easier to read"
gettext "Biggest"
gettext "Large text"
gettext "%1, %2 percent"
gettext "Text size set to %1 percent."
gettext "You can change this again in System Settings ▸ Display & Monitor."
gettext "Where should the taskbar go?"
gettext "Click one to try it. Your open windows and apps stay exactly where they are."
gettext "Taskbar layout"
gettext "Arrow keys to move between layouts, Space to try one"
gettext "%1 taskbar applied."
gettext "Bring your files across."
gettext "There's a Windows drive in this PC. Dagric can copy your Documents, Pictures, Music, Videos, Downloads and browser bookmarks over."
gettext "Windows is only ever READ."
gettext "Windows is only ever read."
gettext "Nothing on the Windows drive is moved, changed or deleted, and files already here are never overwritten. If you change your mind about Dagric, Windows is exactly as you left it."
gettext "Bring my files over"
gettext "Opens the migration tool in its own window. Nothing on the Windows drive is changed."
gettext "This opens in its own window — carry on here while it works."
gettext "Not now? It's in the Dagric Hub under \"Migrate from Windows\", any time."
gettext "That's it — %1 is yours."
gettext "Four places worth knowing about. Everything else you can find by pressing the launcher and typing."
gettext "Dagric Hub"
gettext "Drivers, setup, security and migration, all in one menu."
gettext "User Guide"
gettext "Your first week: updates, printers, Wi-Fi, shortcuts."
gettext "App Manual"
gettext "A page on every app, and what it replaced on Windows."
gettext "Welcome page"
gettext "What Dagric is, and the promises it makes."
gettext "Open"
gettext "Open %1"
gettext "Your desktop is back the way it was."

# TRANSLATORS: name of the "classic" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Classic"
# TRANSLATORS: one-line description of the "classic" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a taskbar at the bottom, familiar and comfortable"
# TRANSLATORS: name of the "command" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Command"
# TRANSLATORS: one-line description of the "command" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a side dock for living in your apps"
# TRANSLATORS: name of the "duo" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Duo"
# TRANSLATORS: one-line description of the "duo" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "two panels, top and bottom, for power users"
# TRANSLATORS: name of the "eleven" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Eleven"
# TRANSLATORS: one-line description of the "eleven" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a centered taskbar, clean and modern"
# TRANSLATORS: name of the "focus" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Focus"
# TRANSLATORS: one-line description of the "focus" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "one tidy bar, nothing in your way"
# TRANSLATORS: name of the "horizon" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Horizon"
# TRANSLATORS: one-line description of the "horizon" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a menu bar up top with a dock below"
# TRANSLATORS: name of the "unity" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Unity"
# TRANSLATORS: one-line description of the "unity" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a side dock with a global menu bar on top"
# TRANSLATORS: name of the "classy" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Classy"
# TRANSLATORS: one-line description of the "classy" desktop style, shown
# under its name. Keep it short.
gettext "dark glass and amber, quietly luxurious"
# TRANSLATORS: name of the "dawn" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Dawn"
# TRANSLATORS: one-line description of the "dawn" desktop style, shown
# under its name. Keep it short.
gettext "light and airy with a soft warm accent"
# TRANSLATORS: name of the "daybreak" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Daybreak"
# TRANSLATORS: one-line description of the "daybreak" desktop style, shown
# under its name. Keep it short.
gettext "the Dagric default: bright, blue, calm"
# TRANSLATORS: name of the "forest" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Forest"
# TRANSLATORS: one-line description of the "forest" desktop style, shown
# under its name. Keep it short.
gettext "calm green for long working days"
# TRANSLATORS: name of the "highcontrast" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "High Contrast"
# TRANSLATORS: one-line description of the "highcontrast" desktop style, shown
# under its name. Keep it short.
gettext "black and white, gold focus ring, no soft effects"
# TRANSLATORS: name of the "midnight" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Midnight"
# TRANSLATORS: one-line description of the "midnight" desktop style, shown
# under its name. Keep it short.
gettext "deep dark, easy on the eyes at night"
# TRANSLATORS: name of the "neon" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Neon"
# TRANSLATORS: one-line description of the "neon" desktop style, shown
# under its name. Keep it short.
gettext "electric cyan, blur and wobbly windows"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dawn"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dusk"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Forest"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Midnight"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Neon"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void Clean"
