#!/bin/sh
# GENERATED by tools/i18n-extract.sh — DO NOT EDIT, DO NOT SHIP.
#
# This file is never installed and never run. It exists so that xgettext
# can see the strings that live in Dagric's DATA files — the .look,
# .style and .iconstyle drop-ins and the wallpaper packs — which reach
# the owner through
# dg_tr() at runtime, i.e. through a variable that xgettext cannot follow.
#
# Regenerate with:  sh tools/i18n-extract.sh

# TRANSLATORS: the setup wizard's own buttons, headings and labels.
# Keep button labels short; they sit in fixed-width buttons beside
# each other. %1 and %2 are values substituted at runtime and may be
# reordered to suit the language.
gettext "Set Up Dagric"
gettext "Try a size here. Keep it within 20 seconds, or Dagric puts it back. This changes text and icons on all screens."
gettext "Keep this size? Restoring in %1 seconds."
gettext "Keep this size"
gettext "Put it back"
gettext "This size could not be applied safely. Your previous size will be restored."
gettext "Your taskbar choice will be applied when you finish setup."
gettext "Every step can be skipped, and you can change all of it later."
gettext "I'll do this later"
gettext "Close setup. Anything already applied stays, and you can run this again from the Dagric Hub"
gettext "Undo my changes"
gettext "Put the colours, wallpaper, text size and taskbar back the way they were when setup opened"
gettext "PRO EDITION"
gettext "Pro edition"
gettext "Live trial — anything you set here lasts until you shut down."
gettext "Back"
gettext "Go back to the previous step"
gettext "Next"
gettext "Go to the next step"
gettext "Finish"
gettext "Close setup and start using Dagric"
gettext "Skip this step"
gettext "Leave this setting alone and go to the next step"
gettext "Let's go"
gettext "Welcome"
gettext "How it looks"
gettext "Text size"
gettext "The taskbar"
gettext "Your files"
gettext "You're ready"
gettext "Step %1"
gettext "Step %1 of %2"
gettext "current step"
gettext "done"
gettext "not done yet"
gettext "Welcome to %1."
gettext "Let's make it yours. A few minutes now — the colours, the wallpaper, how big the text is, where the taskbar sits, and your files from Windows — and then it's out of your way."
gettext "Let's make it yours. A few minutes now — the colours, the wallpaper, how big the text is, where the taskbar sits — and then it's out of your way."
gettext "Pick a look."
gettext "Click anything — the desktop behind this window changes as you go."
gettext "Theme"
gettext "Light"
gettext "Dark"
gettext "Light theme"
gettext "A bright desktop. Shows a small picture of what it looks like."
gettext "Dark theme"
gettext "A dark desktop, easier on the eyes at night."
gettext "Light theme applied."
gettext "Dark theme applied."
gettext "Highlight colour"
gettext "%1 highlight colour applied."
gettext "Wallpaper"
gettext "Wallpaper %1 of %2"
gettext "Arrow keys to move between wallpapers, Space to apply one"
gettext "%1 wallpaper applied."
gettext "Want your own picture? Right-click the desktop and choose Configure Desktop."
gettext "Is the text the right size?"
gettext "Dagric guessed from your screen. A change here takes effect the next time you sign in."
gettext "Normal"
gettext "Standard size"
gettext "Bigger"
gettext "Easier to read"
gettext "Biggest"
gettext "Large text"
gettext "%1, %2 percent"
gettext "You can change this again in System Settings ▸ Display & Monitor."
gettext "Where should the taskbar go?"
gettext "Taskbar layout"
gettext "Arrow keys to move between layouts, Space to try one"
gettext "Bring your files across."
gettext "There's a Windows drive in this PC. Dagric can copy your Documents, Pictures, Music, Videos, Downloads and browser bookmarks over."
gettext "Windows is only ever READ."
gettext "Windows is only ever read."
gettext "Nothing on the Windows drive is moved, changed or deleted, and files already here are never overwritten. If you change your mind about Dagric, Windows is exactly as you left it."
gettext "Bring my files over"
gettext "Opens the migration tool in its own window. Nothing on the Windows drive is changed."
gettext "This opens in its own window — carry on here while it works."
gettext "Not now? It's in the Dagric Hub under \"Migrate from Windows\", any time."
gettext "That's it — %1 is yours."
gettext "Four places worth knowing about. Everything else you can find by pressing the launcher and typing."
gettext "Dagric Hub"
gettext "Drivers, setup, security and migration, all in one menu."
gettext "User Guide"
gettext "Your first week: updates, printers, Wi-Fi, shortcuts."
gettext "App Manual"
gettext "A page on every app, and what it replaced on Windows."
gettext "Welcome page"
gettext "What Dagric is, and the promises it makes."
gettext "Open"
gettext "Open %1"
gettext "Your desktop is back the way it was."
gettext "You're running the live trial from the USB stick, so anything you set here lasts until you shut down. Install Dagric first if you want it to stick."
gettext "This is the live trial. To keep any of it, run Install Dagric OS from the desktop."
gettext "Want to run through this again? It's called \"Set Up Dagric\" in your apps list."
gettext "Add your apps"
gettext "Choose what you want. Each installer opens after Finish and asks before making changes. Some choices are third-party or proprietary; none is required."
gettext "Steam"
gettext "Optional proprietary Valve client; vendor terms apply."
gettext "Heroic"
gettext "Independent launcher for Epic Games Store, GOG and Amazon Games."
gettext "Bottles"
gettext "Run Windows programs in separate Wine environments."
gettext "ONLYOFFICE"
gettext "An office suite that looks like the one at work."
gettext "Joplin"
gettext "Private notes that sync anywhere."
gettext "LocalSend"
gettext "Share files between your devices, no cloud."
gettext "Cryptomator"
gettext "Encrypt what you keep in the cloud."
gettext "Upscayl"
gettext "Sharpen old photos with AI."
gettext "Ollama"
gettext "A local AI that never leaves this machine."
gettext "Already bought Pro?"
gettext "Paste the code from your receipt and this machine becomes Pro — your files and settings stay."
gettext "Selected — starts when you press Finish."
gettext "Selected"
gettext "This is the live trial: anything you add now lives in memory, disappears at shutdown, and can make a machine with little RAM unstable. Install Dagric first to keep it."
gettext "Nothing here is a subscription, and everything can be removed later from the Software Store."

# TRANSLATORS: the Family Limits window's own buttons, headings and labels.
# Keep button labels short; they sit in fixed-width buttons beside
# each other. %1 and %2 are values substituted at runtime and may be
# reordered to suit the language.
gettext "Family Limits"
gettext "Set how long someone can use this computer each day, and the hours when it locks itself. Their files and their account are not touched."
gettext "Person:"
gettext "Person to set limits for"
gettext "This is the only administrator account on this computer. Limits cannot be set on it, because there would be no way back in. Create a second administrator account first."
gettext "This person has not signed in yet, so there is nothing to change. Ask them to sign in once, then come back."
gettext "Limit this person's screen time"
gettext "Time allowed each day"
gettext "Time allowed each day: %1"
gettext "Bedtime: none — the computer never locks by the clock"
gettext "The computer locks from %1 to %2"
gettext "From"
gettext "until"
gettext "Bedtime starts at"
gettext "Bedtime ends at"
gettext "Set both to the same hour for no bedtime at all."
gettext "When the time is up:"
gettext "Lock the screen — nothing is closed, nothing is lost"
gettext "Sign out — closes everything that is open"
gettext "Remove all limits"
gettext "Lets this person use the computer at any time, for as long as they like"
gettext "Close"
gettext "Save"
gettext "Save these limits for %1"
gettext "%1 minutes"
gettext "1 hour"
gettext "%1 hours"
gettext "%1 h %2 min"

# TRANSLATORS: name of the "classic" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Classic"
# TRANSLATORS: one-line description of the "classic" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a taskbar at the bottom, familiar and comfortable"
# TRANSLATORS: name of the "command" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Command"
# TRANSLATORS: one-line description of the "command" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "the same side dock, but each window keeps its own menu bar"
# TRANSLATORS: name of the "duo" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Duo"
# TRANSLATORS: one-line description of the "duo" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "two panels, top and bottom, for power users"
# TRANSLATORS: name of the "eleven" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Centered"
# TRANSLATORS: one-line description of the "eleven" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a centered taskbar, clean and modern"
# TRANSLATORS: name of the "focus" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Focus"
# TRANSLATORS: one-line description of the "focus" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "one tidy bar, nothing in your way"
# TRANSLATORS: name of the "horizon" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Horizon"
# TRANSLATORS: one-line description of the "horizon" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a menu bar up top with a dock below"
# TRANSLATORS: name of the "unity" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Unity"
# TRANSLATORS: one-line description of the "unity" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a side dock, with every window's menu moved to the top bar"
# TRANSLATORS: name of the "classy" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Classy"
# TRANSLATORS: one-line description of the "classy" desktop style, shown
# under its name. Keep it short.
gettext "dark glass and amber, quietly luxurious"
# TRANSLATORS: name of the "dawn" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Dawn"
# TRANSLATORS: one-line description of the "dawn" desktop style, shown
# under its name. Keep it short.
gettext "light and airy with a soft warm accent"
# TRANSLATORS: name of the "daybreak" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Daybreak"
# TRANSLATORS: one-line description of the "daybreak" desktop style, shown
# under its name. Keep it short.
gettext "bright, quiet and practical"
# TRANSLATORS: name of the "forest" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Forest"
# TRANSLATORS: one-line description of the "forest" desktop style, shown
# under its name. Keep it short.
gettext "calm green for long working days"
# TRANSLATORS: name of the "highcontrast" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "High Contrast"
# TRANSLATORS: one-line description of the "highcontrast" desktop style, shown
# under its name. Keep it short.
gettext "black and white, gold focus ring, no soft effects"
# TRANSLATORS: name of the "midnight" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Midnight"
# TRANSLATORS: one-line description of the "midnight" desktop style, shown
# under its name. Keep it short.
gettext "deep dark, easy on the eyes at night"
# TRANSLATORS: name of the "neon" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Neon"
# TRANSLATORS: one-line description of the "neon" desktop style, shown
# under its name. Keep it short.
gettext "electric cyan, blur and wobbly windows"
# TRANSLATORS: name of the "night-orbit" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Night Orbit"
# TRANSLATORS: one-line description of the "night-orbit" desktop style, shown
# under its name. Keep it short.
gettext "aubergine, magenta and orange after dark"
# TRANSLATORS: name of the "obsidian-flow" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Obsidian Flow"
# TRANSLATORS: one-line description of the "obsidian-flow" desktop style, shown
# under its name. Keep it short.
gettext "dark material, calm motion, focused gaming"
# TRANSLATORS: name of the "open-coast" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Open Coast"
# TRANSLATORS: one-line description of the "open-coast" desktop style, shown
# under its name. Keep it short.
gettext "turquoise, coral and sand with open water"
# TRANSLATORS: name of the "open-horizon" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Open Horizon"
# TRANSLATORS: one-line description of the "open-horizon" desktop style, shown
# under its name. Keep it short.
gettext "warm amber space with a distant open view"
# TRANSLATORS: name of the "wild-meadow" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Wild Meadow"
# TRANSLATORS: one-line description of the "wild-meadow" desktop style, shown
# under its name. Keep it short.
gettext "sage, moss and sunlight for a calm workspace"
# TRANSLATORS: name of the "classic" icon family in Dagric Appearance.
# One or two words, shown as the title of a picture tile.
gettext "Classic"
# TRANSLATORS: one-line description of the "classic" icon family, shown
# under its name. Keep it short.
gettext "Warm enamel badges inspired by durable desktop tools."
# TRANSLATORS: name of the "modern" icon family in Dagric Appearance.
# One or two words, shown as the title of a picture tile.
gettext "Modern"
# TRANSLATORS: one-line description of the "modern" icon family, shown
# under its name. Keep it short.
gettext "Vivid dimensional icons with crisp silhouettes."
# TRANSLATORS: name of the "old-school" icon family in Dagric Appearance.
# One or two words, shown as the title of a picture tile.
gettext "Old School"
# TRANSLATORS: one-line description of the "old-school" icon family, shown
# under its name. Keep it short.
gettext "Friendly pixel icons inspired by early personal computers."
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dawn"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dusk"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Forest"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Midnight"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Neon"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Night Orbit"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Obsidian Pulse"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Open Coast"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Open Horizon"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Wild Meadow"
