#!/bin/sh
# GENERATED by tools/i18n-extract.sh — DO NOT EDIT, DO NOT SHIP.
#
# This file is never installed and never run. It exists so that xgettext
# can see the strings that live in Dagric's DATA files — the .look and
# .style drop-ins and the wallpaper packs — which reach the owner through
# dg_tr() at runtime, i.e. through a variable that xgettext cannot follow.
#
# Regenerate with:  sh tools/i18n-extract.sh

# TRANSLATORS: name of the "classic" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Classic"
# TRANSLATORS: one-line description of the "classic" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a taskbar at the bottom, familiar and comfortable"
# TRANSLATORS: name of the "command" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Command"
# TRANSLATORS: one-line description of the "command" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a side dock for living in your apps"
# TRANSLATORS: name of the "duo" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Duo"
# TRANSLATORS: one-line description of the "duo" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "two panels, top and bottom, for power users"
# TRANSLATORS: name of the "eleven" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Eleven"
# TRANSLATORS: one-line description of the "eleven" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a centered taskbar, clean and modern"
# TRANSLATORS: name of the "focus" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Focus"
# TRANSLATORS: one-line description of the "focus" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "one tidy bar, nothing in your way"
# TRANSLATORS: name of the "horizon" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Horizon"
# TRANSLATORS: one-line description of the "horizon" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a menu bar up top with a dock below"
# TRANSLATORS: name of the "unity" taskbar layout in Dagric Looks and the
# setup wizard. One or two words, shown as the title of a picture tile.
gettext "Unity"
# TRANSLATORS: one-line description of the "unity" taskbar layout, shown
# under its name. Keep it short — it has to fit on one line beside a tile.
gettext "a side dock with a global menu bar on top"
# TRANSLATORS: name of the "classy" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Classy"
# TRANSLATORS: one-line description of the "classy" desktop style, shown
# under its name. Keep it short.
gettext "dark glass and amber, quietly luxurious"
# TRANSLATORS: name of the "dawn" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Dawn"
# TRANSLATORS: one-line description of the "dawn" desktop style, shown
# under its name. Keep it short.
gettext "light and airy with a soft warm accent"
# TRANSLATORS: name of the "daybreak" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Daybreak"
# TRANSLATORS: one-line description of the "daybreak" desktop style, shown
# under its name. Keep it short.
gettext "the Dagric default: bright, blue, calm"
# TRANSLATORS: name of the "forest" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Forest"
# TRANSLATORS: one-line description of the "forest" desktop style, shown
# under its name. Keep it short.
gettext "calm green for long working days"
# TRANSLATORS: name of the "highcontrast" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "High Contrast"
# TRANSLATORS: one-line description of the "highcontrast" desktop style, shown
# under its name. Keep it short.
gettext "black and white, gold focus ring, no soft effects"
# TRANSLATORS: name of the "midnight" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Midnight"
# TRANSLATORS: one-line description of the "midnight" desktop style, shown
# under its name. Keep it short.
gettext "deep dark, easy on the eyes at night"
# TRANSLATORS: name of the "neon" desktop style (colours, wallpaper and
# effects) in Dagric Styles and the appearance gallery. One or two words.
gettext "Neon"
# TRANSLATORS: one-line description of the "neon" desktop style, shown
# under its name. Keep it short.
gettext "electric cyan, blur and wobbly windows"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Arctic Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Aurora Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Contour Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Copper Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dawn"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Dusk"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ember Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Forest"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Halftone Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Ink Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Linen Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Mesh Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Midnight"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Neon"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Prism Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Sand Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Slate Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Violet Clean"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void"
# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand
# and never changes; translate only the descriptive word after it.
gettext "Dagric Void Clean"
