#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 DGR Operations <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Dagric OS -- write the localised keys into Dagric's own launcher entries.
#
#     python3 tools/i18n-desktop.py            update the .desktop files
#     python3 tools/i18n-desktop.py --check    verify only, change nothing
#
# WHY THIS IS NOT gettext
# -----------------------
# A .desktop file carries EVERY language at once:
#
#     Name=Migrate from Windows
#     Name[de]=Von Windows umziehen
#     Name[fr]=Migrer depuis Windows
#
# The desktop picks one by matching the LC_MESSAGES locale against the
# postfixes -- lang_COUNTRY@MOD, then lang_COUNTRY, then lang@MOD, then lang,
# then the unlocalised key. A locale with no entry falls back to the plain
# Name= with nothing to configure and nothing that can break. There is no
# runtime, no library and no catalogue lookup involved, which makes this the
# cheapest localisation win in the whole product -- and the reason the keys are
# written into the files rather than looked up.
#
# The file is the deliverable; this script is the maintainable source for it.
# Run it after editing any English Name/GenericName/Comment so the translations
# and the source cannot drift apart silently -- --check is what catches that.
#
# KEYWORDS ARE ADDITIVE, NEVER REPLACED
# -------------------------------------
# Keywords= is a search index, not prose, and it is the one field where machine
# translation reliably produces nonsense: "dolphin;explorer;this pc;" comes back
# with the fish and a literal "dieser PC", losing the actual German Windows
# terms a switcher would type. So Keywords[xx] is built as
#
#     the original English list  +  a short native list written by hand
#
# Nothing is ever taken away. A German owner can still find "Files" by typing
# "explorer" or "dolphin", and now also by typing "Dateien". If the native list
# for a language is empty, no Keywords[xx] is emitted at all and the English
# Keywords= applies -- which is exactly right, and is why the additions below
# are short and specific rather than a full translation of every term.
import os
import sys
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
APPS = os.path.join(ROOT, 'config/includes.chroot/usr/share/applications')
LANGS = ['de', 'fr', 'es', 'pt_BR', 'it']

MARK = ('# Localised keys below are generated by tools/i18n-desktop.py.\n'
        '# Machine translation, unreviewed -- see the header of po/de.po.\n'
        '# Edit the table in that script, not these lines.\n')

# id -> { lang: (Name, GenericName, Comment, extra-keywords) }
# extra-keywords is APPENDED to the English Keywords=; "" means emit none.
D = {}

# The two accessibility entries. They lived as heredocs inside
# 0530-accessibility.hook.chroot, where this script could never see them, so
# they shipped English-only in every translated language — and their Keywords
# are the entire point of the files: they are what somebody types when they do
# not know what the feature is called on Linux. The native keyword lists below
# are ADDITIVE, keeping the English terms, because a German owner who learned
# "screen reader" from an English forum post must still find it.
D['dagric-screen-reader'] = {
 'de': ("Bildschirmleser", "Liest den Bildschirm vor (Orca)",
        "Den Bildschirm vorlesen lassen. Mit Meta+Alt+S jederzeit ein- oder ausschalten.",
        "bildschirmleser;vorlesen;sprachausgabe;vorleseprogramm;blind;blindheit;sehbehindert;sehbehinderung;sprache;braille;barrierefreiheit;"),
 'fr': ("Lecteur d'écran", "Lit l'écran à voix haute (Orca)",
        "Faire lire l'écran à voix haute. Meta+Alt+S pour activer ou désactiver à tout moment.",
        "lecteur d'écran;lecture d'écran;synthèse vocale;vocal;aveugle;cécité;malvoyant;braille;accessibilité;"),
 'es': ("Lector de pantalla", "Lee la pantalla en voz alta (Orca)",
        "Hacer que la pantalla se lea en voz alta. Pulsa Meta+Alt+S para activarlo o desactivarlo.",
        "lector de pantalla;lectura de pantalla;voz;síntesis de voz;ciego;ceguera;baja visión;braille;accesibilidad;"),
 'pt_BR': ("Leitor de tela", "Lê a tela em voz alta (Orca)",
        "Fazer a tela ser lida em voz alta. Pressione Meta+Alt+S para ligar ou desligar.",
        "leitor de tela;leitura de tela;voz;síntese de voz;cego;cegueira;baixa visão;braille;acessibilidade;"),
 'it': ("Lettore dello schermo", "Legge lo schermo ad alta voce (Orca)",
        "Far leggere lo schermo ad alta voce. Premi Meta+Alt+S per attivarlo o disattivarlo.",
        "lettore dello schermo;lettura schermo;sintesi vocale;voce;cieco;cecità;ipovedente;braille;accessibilità;"),
}
# NOTE ON THE Comment ROWS BELOW: none of them names slow keys, and none of
# them should. kaccess still offers the switch, but kwin 4:6.3.6-1 ships no
# SlowKeysPlugin and the fallback (XkbSetControls) reaches XWayland clients
# only, while Dagric's session is Wayland — so the feature ticks on and does
# nothing. /etc/skel/.config/kaccessrc argues it in full and
# site/accessibility.html reports 508 502.4(B) as "Does Not Support"; a launcher
# entry that advertises it anyway is the same defect as a script printing a
# success it did not achieve, in five languages at once. The slow-keys terms
# stay in the Keywords rows, because those are a search index and somebody
# hunting for the feature should still find this panel. Comment is a promise.
D['dagric-accessibility'] = {
 'de': ("Bedienungshilfen", "Den Computer leichter bedienbar machen",
        "Bildschirmleser, Lupe, hoher Kontrast, Einrastfunktion, Tastenanschlagsperre, Tastaturmaus",
        "bedienungshilfen;erleichterte bedienung;barrierefreiheit;behinderung;lupe;vergrößerung;vergrössern;zoom;hoher kontrast;kontrast;farbenblind;farbfehlsichtig;einrastfunktion;anschlagverzögerung;tastaturmaus;schwerhörig;gehörlos;sehbehindert;großer mauszeiger;"),
 'fr': ("Accessibilité", "Rendre l'ordinateur plus facile à utiliser",
        "Lecteur d'écran, loupe, contraste élevé, touches rémanentes, rebonds de touches, touches souris",
        "accessibilité;facilité d'accès;handicap;loupe;agrandissement;zoom;contraste élevé;contraste;daltonien;daltonisme;touches rémanentes;touches lentes;touches filtres;touches souris;malentendant;sourd;malvoyant;grand curseur;"),
 'es': ("Accesibilidad", "Hacer que el ordenador sea más fácil de usar",
        "Lector de pantalla, lupa, alto contraste, teclas persistentes, teclas de rebote, teclas del ratón",
        "accesibilidad;facilidad de acceso;discapacidad;lupa;ampliación;zoom;alto contraste;contraste;daltónico;daltonismo;teclas persistentes;teclas lentas;teclas de filtro;teclas del ratón;sordo;con problemas de audición;baja visión;cursor grande;"),
 'pt_BR': ("Acessibilidade", "Deixar o computador mais fácil de usar",
        "Leitor de tela, lupa, alto contraste, teclas de aderência, teclas de repercussão, teclas do mouse",
        "acessibilidade;facilidade de acesso;deficiência;lupa;ampliação;zoom;alto contraste;contraste;daltônico;daltonismo;teclas de aderência;teclas lentas;teclas de filtro;teclas do mouse;surdo;deficiência auditiva;baixa visão;cursor grande;"),
 'it': ("Accessibilità", "Rendere il computer più facile da usare",
        "Lettore dello schermo, lente, contrasto elevato, permanenza dei tasti, tasti ravvicinati, mouse da tastiera",
        "accessibilità;facilità di accesso;disabilità;lente;ingrandimento;zoom;contrasto elevato;contrasto;daltonico;daltonismo;permanenza dei tasti;tasti lenti;tasti filtro;mouse da tastiera;sordo;problemi di udito;ipovedente;cursore grande;"),
}

D['dagric-hub'] = {
 'de': ("Dagric Hub", "Dagric-Werkzeuge und Einrichtung",
        "Ein Ort für Treiber, Einrichtung, Sicherheit, das Handbuch und die Pro-Kreativwerkzeuge",
        "werkzeuge;einrichten;treiber;sicherheit;anleitung;"),
 'fr': ("Dagric Hub", "Outils et configuration Dagric",
        "Un seul endroit pour les pilotes, la configuration, la sécurité, le guide et les outils créatifs Pro",
        "outils;configuration;pilotes;sécurité;guide;"),
 'es': ("Dagric Hub", "Herramientas y configuración de Dagric",
        "Un único sitio para controladores, configuración, seguridad, la guía y las herramientas creativas de Pro",
        "herramientas;configuración;controladores;seguridad;guía;"),
 'pt_BR': ("Dagric Hub", "Ferramentas e configuração do Dagric",
        "Um só lugar para drivers, configuração, segurança, o guia e as ferramentas criativas do Pro",
        "ferramentas;configuração;drivers;segurança;guia;"),
 'it': ("Dagric Hub", "Strumenti e configurazione Dagric",
        "Un unico posto per driver, configurazione, sicurezza, la guida e gli strumenti creativi Pro",
        "strumenti;configurazione;driver;sicurezza;guida;"),
}
# Family Limits. The launcher name must match what the WINDOW calls itself --
# po/*.po translate the title "Family Limits" and a parent who opens
# "Familienzeiten" from the menu and lands in a window headed "Familienlimits"
# has been handed two names for one thing. These are the catalogue's terms:
# screen time = Bildschirmzeit / tiempo de pantalla / temps d'ecran /
# tempo di utilizzo / tempo de tela, and bedtime = Schlafenszeit /
# hora de dormir / heure du coucher / orario di riposo / horario de dormir.
D['dagric-family'] = {
 'de': ("Familienlimits", "Bildschirmzeit und Schlafenszeit",
        "Tägliche Bildschirmzeit und Schlafenszeit für ein Familienmitglied festlegen",
        "kindersicherung;kinder;bildschirmzeit;schlafenszeit;familie;limits;"),
 'fr': ("Limites familiales", "Temps d'écran et heure du coucher",
        "Définir le temps d'écran quotidien et l'heure du coucher d'un proche",
        "contrôle parental;enfants;temps d'écran;heure du coucher;famille;limites;"),
 'es': ("Límites familiares", "Tiempo de pantalla y hora de dormir",
        "Establece el tiempo de pantalla diario y la hora de dormir de un familiar",
        "control parental;niños;tiempo de pantalla;hora de dormir;familia;límites;"),
 'pt_BR': ("Limites da família", "Tempo de tela e horário de dormir",
        "Defina o tempo de tela diário e o horário de dormir de um familiar",
        "controle dos pais;crianças;tempo de tela;horário de dormir;família;limites;"),
 'it': ("Limiti famiglia", "Tempo di utilizzo e orario di riposo",
        "Imposta il tempo di utilizzo giornaliero e l'orario di riposo di un familiare",
        "controllo genitori;bambini;tempo di utilizzo;orario di riposo;famiglia;limiti;"),
}

D['dagric-firstrun'] = {
 'de': ("Dagric einrichten", "Willkommens- und Einrichtungsassistent",
        "Wählen Sie Farben, Hintergrundbild, Schriftgröße und Taskleiste, und holen Sie Ihre Dateien von Windows herüber",
        "willkommen;einrichten;erster start;assistent;anpassen;farben;hintergrundbild;dunkelmodus;schriftgröße;taskleiste;umziehen;"),
 'fr': ("Configurer Dagric", "Assistant de bienvenue et de configuration",
        "Choisissez vos couleurs, votre fond d'écran, la taille du texte et la barre des tâches, et récupérez vos fichiers depuis Windows",
        "bienvenue;configuration;premier démarrage;assistant;personnaliser;couleurs;fond d'écran;mode sombre;taille du texte;barre des tâches;migration;"),
 'es': ("Configurar Dagric", "Asistente de bienvenida y configuración",
        "Elige colores, fondo de pantalla, tamaño de texto y barra de tareas, y trae tus archivos desde Windows",
        "bienvenida;configuración;primer inicio;asistente;personalizar;colores;fondo de pantalla;modo oscuro;tamaño de texto;barra de tareas;migrar;"),
 'pt_BR': ("Configurar o Dagric", "Assistente de boas-vindas e configuração",
        "Escolha cores, papel de parede, tamanho do texto e barra de tarefas, e traga seus arquivos do Windows",
        "boas-vindas;configuração;primeiro início;assistente;personalizar;cores;papel de parede;modo escuro;tamanho do texto;barra de tarefas;migrar;"),
 'it': ("Configura Dagric", "Procedura di benvenuto e configurazione",
        "Scegli colori, sfondo, dimensione del testo e barra delle applicazioni, e porta i tuoi file da Windows",
        "benvenuto;configurazione;primo avvio;procedura guidata;personalizza;colori;sfondo;modalità scura;dimensione del testo;barra delle applicazioni;migrazione;"),
}
D['dagric-migrate'] = {
 'de': ("Von Windows umziehen", "Windows-Migrationsassistent",
        "Kopiert Ihre Dokumente, Bilder, Musik, Videos und Browser-Lesezeichen von dem Windows auf diesem PC herüber",
        "windows;umzug;umziehen;übertragen;dateien;dokumente;lesezeichen;wechseln;"),
 'fr': ("Migrer depuis Windows", "Assistant de migration Windows",
        "Copie vos Documents, Images, Musique, Vidéos et favoris de navigateur depuis le Windows installé sur ce PC",
        "windows;migration;migrer;transférer;fichiers;documents;favoris;changer;"),
 'es': ("Migrar desde Windows", "Asistente de migración de Windows",
        "Copia tus Documentos, Imágenes, Música, Vídeos y marcadores del navegador desde el Windows de este PC",
        "windows;migración;migrar;transferir;archivos;documentos;marcadores;cambiar;"),
 'pt_BR': ("Migrar do Windows", "Assistente de migração do Windows",
        "Copia seus Documentos, Imagens, Músicas, Vídeos e favoritos do navegador a partir do Windows deste PC",
        "windows;migração;migrar;transferir;arquivos;documentos;favoritos;trocar;"),
 'it': ("Migra da Windows", "Assistente di migrazione da Windows",
        "Copia i tuoi Documenti, Immagini, Musica, Video e i segnalibri del browser dal Windows presente su questo PC",
        "windows;migrazione;migrare;trasferire;file;documenti;segnalibri;passaggio;"),
}
D['dagric-setup'] = {
 'de': ("Einrichtung abschließen", "Diesen PC einrichten",
        "Grafik- und Druckertreiber installieren und die Einrichtung von Dagric abschließen",
        "einrichten;treiber;drucker;abschließen;"),
 'fr': ("Terminer la configuration", "Configurer ce PC",
        "Installer les pilotes graphiques et d'imprimante et terminer la configuration de Dagric",
        "configuration;pilotes;imprimante;terminer;"),
 'es': ("Terminar configuración", "Configurar este PC",
        "Instalar los controladores de gráficos e impresora y terminar de configurar Dagric",
        "configuración;controladores;impresora;terminar;"),
 'pt_BR': ("Concluir configuração", "Configurar este PC",
        "Instalar os drivers de vídeo e de impressora e concluir a configuração do Dagric",
        "configuração;drivers;impressora;concluir;"),
 'it': ("Completa la configurazione", "Configura questo PC",
        "Installa i driver grafici e della stampante e completa la configurazione di Dagric",
        "configurazione;driver;stampante;completare;"),
}
# THIS TABLE IS THE SOURCE OF TRUTH, so the debranding had to happen here.
# Editing dagric-drivers.desktop directly would have looked correct and been
# undone by the next run of this script — the file carries a header saying as
# much, and that is exactly the trap: a rebranding that survives review and
# dies at the next regeneration.
D['dagric-drivers'] = {
 'de': ("Grafiktreiber", "Proprietäre GPU-Treiber installieren",
        "Erkennt eine NVIDIA-Grafikkarte und installiert ihren Treiber aus der Non-free-Paketquelle des Systems",
        "treiber;grafik;grafikkarte;hardware;"),
 'fr': ("Pilotes graphiques", "Installer les pilotes GPU propriétaires",
        "Détecte une carte NVIDIA et installe son pilote depuis le dépôt non-free du système",
        "pilote;graphique;carte graphique;matériel;"),
 'es': ("Controladores gráficos", "Instalar controladores propietarios de GPU",
        "Detecta una tarjeta NVIDIA e instala su controlador desde el repositorio non-free del sistema",
        "controlador;gráficos;tarjeta gráfica;hardware;"),
 'pt_BR': ("Drivers de vídeo", "Instalar drivers proprietários de GPU",
        "Detecta uma placa NVIDIA e instala o driver dela a partir do repositório non-free do sistema",
        "driver;vídeo;placa de vídeo;hardware;"),
 'it': ("Driver grafici", "Installa i driver GPU proprietari",
        "Rileva una scheda NVIDIA e installa il suo driver dal repository non-free del sistema",
        "driver;grafica;scheda video;hardware;"),
}
D['dagric-display'] = {
 'de': ("Schriftgröße", "Schriftgröße und Nachtfarben",
        "Alles auf dem Bildschirm größer machen und die Farben abends wärmer stellen",
        "bildschirm;schriftgröße;größer;zu klein;vergrößern;skalierung;nachtfarben;blaulichtfilter;augen;alles ist zu klein;"),
 'fr': ("Taille du texte", "Taille du texte et couleur nocturne",
        "Agrandir tout ce qui est à l'écran et réchauffer les couleurs le soir",
        "écran;taille du texte;plus grand;trop petit;agrandir;mise à l'échelle;lumière nocturne;filtre lumière bleue;yeux;tout est trop petit;"),
 'es': ("Tamaño del texto", "Tamaño del texto y color nocturno",
        "Hacer todo más grande en la pantalla y dar calidez a los colores por la tarde",
        "pantalla;tamaño de texto;más grande;demasiado pequeño;ampliar;escalado;luz nocturna;filtro de luz azul;vista;todo es muy pequeño;"),
 'pt_BR': ("Tamanho do texto", "Tamanho do texto e cor noturna",
        "Deixar tudo maior na tela e esquentar as cores à noite",
        "tela;tamanho do texto;maior;pequeno demais;ampliar;escala;luz noturna;filtro de luz azul;olhos;está tudo pequeno demais;"),
 'it': ("Dimensione del testo", "Dimensione del testo e colore notturno",
        "Ingrandire tutto sullo schermo e scaldare i colori la sera",
        "schermo;dimensione del testo;più grande;troppo piccolo;ingrandire;ridimensionamento;luce notturna;filtro luce blu;occhi;è tutto troppo piccolo;"),
}
D['dagric-appearance'] = {
 'de': ("Dagric Erscheinungsbild", "Galerie des Erscheinungsbilds",
        "Sehen Sie jeden Stil und jedes Layout als Bild, probieren Sie eines aus und behalten Sie es nur, wenn es Ihnen gefällt",
        "erscheinungsbild;galerie;vorschau;stil;layout;hintergrundbild;farbe;dunkel;hell;"),
 'fr': ("Apparence Dagric", "Galerie d'apparence",
        "Voyez chaque style et chaque disposition en image, essayez-en un pour de vrai, et ne le gardez que s'il vous plaît",
        "apparence;galerie;aperçu;style;disposition;fond d'écran;couleur;sombre;clair;"),
 'es': ("Apariencia de Dagric", "Galería de apariencia",
        "Ve cada estilo y disposición como una imagen, prueba uno de verdad y quédatelo solo si te gusta",
        "apariencia;galería;vista previa;estilo;disposición;fondo de pantalla;color;oscuro;claro;"),
 'pt_BR': ("Aparência do Dagric", "Galeria de aparência",
        "Veja cada estilo e layout como uma imagem, experimente um de verdade e fique com ele só se gostar",
        "aparência;galeria;pré-visualização;estilo;layout;papel de parede;cor;escuro;claro;"),
 'it': ("Aspetto di Dagric", "Galleria dell'aspetto",
        "Guarda ogni stile e disposizione come immagine, provane uno davvero e tienilo solo se ti piace",
        "aspetto;galleria;anteprima;stile;disposizione;sfondo;colore;scuro;chiaro;"),
}
D['dagric-looks'] = {
 'de': ("Dagric Looks", "Desktop-Layout",
        "Wählen Sie Ihr Desktop-Layout — klassische Taskleiste, minimal, Dock und mehr",
        "layout;arbeitsfläche;taskleiste;dock;erscheinungsbild;"),
 'fr': ("Dagric Looks", "Disposition du bureau",
        "Choisissez la disposition de votre bureau — barre des tâches classique, minimale, dock, et plus",
        "disposition;bureau;barre des tâches;dock;apparence;"),
 'es': ("Dagric Looks", "Disposición del escritorio",
        "Elige la disposición de tu escritorio: barra de tareas clásica, minimalista, dock y más",
        "disposición;escritorio;barra de tareas;dock;apariencia;"),
 'pt_BR': ("Dagric Looks", "Layout da área de trabalho",
        "Escolha o layout da sua área de trabalho — barra de tarefas clássica, minimalista, dock e mais",
        "layout;área de trabalho;barra de tarefas;dock;aparência;"),
 'it': ("Dagric Looks", "Disposizione del desktop",
        "Scegli la disposizione del desktop — barra delle applicazioni classica, minimale, dock e altro",
        "disposizione;desktop;barra delle applicazioni;dock;aspetto;"),
}
D['dagric-style'] = {
 'de': ("Dagric Styles", "Stimmungswechsler für den Desktop",
        "Ändern Sie Farben, Hintergrundbild und Effekte der Arbeitsfläche mit einem Klick — die Leisten bleiben, wo sie sind",
        "stil;dunkel;hell;akzent;farbe;hintergrundbild;effekte;erscheinungsbild;"),
 'fr': ("Dagric Styles", "Changeur d'ambiance du bureau",
        "Changez les couleurs, le fond d'écran et les effets du bureau en un clic — les panneaux ne bougent pas",
        "style;sombre;clair;accentuation;couleur;fond d'écran;effets;apparence;"),
 'es': ("Dagric Styles", "Cambiador de ambiente del escritorio",
        "Cambia los colores, el fondo de pantalla y los efectos del escritorio con un clic; los paneles no se mueven",
        "estilo;oscuro;claro;acento;color;fondo de pantalla;efectos;apariencia;"),
 'pt_BR': ("Dagric Styles", "Trocador de clima da área de trabalho",
        "Mude as cores, o papel de parede e os efeitos da área de trabalho com um clique — os painéis ficam onde estão",
        "estilo;escuro;claro;destaque;cor;papel de parede;efeitos;aparência;"),
 'it': ("Dagric Styles", "Cambio atmosfera del desktop",
        "Cambia colori, sfondo ed effetti del desktop con un clic — i pannelli restano dove sono",
        "stile;scuro;chiaro;accento;colore;sfondo;effetti;aspetto;"),
}
D['dagric-manual'] = {
 'de': ("Dagric Handbuch", "Hilfe zu jedem Programm",
        "Jedes Programm auf diesem Computer erklärt — was es unter Windows ersetzt und wie man es benutzt",
        "handbuch;hilfe;anleitung;dokumentation;programme;unterstützung;"),
 'fr': ("Manuel Dagric", "Aide pour chaque application",
        "Chaque application de cet ordinateur expliquée — ce qu'elle remplace sous Windows et comment s'en servir",
        "manuel;aide;guide;documentation;applications;assistance;"),
 'es': ("Manual de Dagric", "Ayuda para cada aplicación",
        "Todas las aplicaciones de este ordenador explicadas: a qué sustituyen de Windows y cómo usarlas",
        "manual;ayuda;guía;documentación;aplicaciones;soporte;"),
 'pt_BR': ("Manual do Dagric", "Ajuda para cada aplicativo",
        "Todos os aplicativos deste computador explicados — o que substituem no Windows e como usar",
        "manual;ajuda;guia;documentação;aplicativos;suporte;"),
 'it': ("Manuale Dagric", "Aiuto per ogni applicazione",
        "Ogni applicazione di questo computer spiegata — che cosa sostituisce su Windows e come si usa",
        "manuale;aiuto;guida;documentazione;applicazioni;assistenza;"),
}
# The user guide. THE NAMES BELOW ARE NOT FREE WORDING: they are the existing
# msgid "User Guide" translations from po/*.po, the ones the setup wizard's last
# screen already shows on its card. The entry used to be called "Welcome Guide"
# (Willkommensanleitung / Guide de bienvenue / ...), which is the Hub's name for
# a DIFFERENT document — the welcome page, run by dagric-welcome — so the two
# collided in the launcher. Keep these in step with po/*.po, not with the
# Keywords list below, which stays additive and keeps "welcome/willkommen/
# bienvenue" searchable for anyone who learned the old name.
D['dagric-guide'] = {
 'de': ("Benutzeranleitung", "Ihre erste Woche mit Dagric",
        "Die kurze Lektüre: Aktualisierungen, Drucker, WLAN, Tastenkürzel und wie die Arbeitsfläche Ihre wird",
        "willkommen;anleitung;hilfe;erste schritte;erste woche;einführung;"),
 'fr': ("Guide de l'utilisateur", "Votre première semaine avec Dagric",
        "La lecture courte : mises à jour, imprimantes, Wi-Fi, raccourcis, et comment faire du bureau le vôtre",
        "bienvenue;guide;aide;premiers pas;première semaine;introduction;"),
 'es': ("Guía del usuario", "Tu primera semana con Dagric",
        "La lectura breve: actualizaciones, impresoras, wifi, atajos y cómo hacer tuyo el escritorio",
        "bienvenida;guía;ayuda;primeros pasos;primera semana;introducción;"),
 'pt_BR': ("Guia do usuário", "Sua primeira semana com o Dagric",
        "A leitura curta: atualizações, impressoras, Wi-Fi, atalhos e como deixar a área de trabalho com a sua cara",
        "boas-vindas;guia;ajuda;primeiros passos;primeira semana;introdução;"),
 'it': ("Guida utente", "La tua prima settimana con Dagric",
        "La lettura breve: aggiornamenti, stampanti, Wi-Fi, scorciatoie e come rendere tuo il desktop",
        "benvenuto;guida;aiuto;primi passi;prima settimana;introduzione;"),
}
D['dagric-security-checkup'] = {
 'de': ("Sicherheitsprüfung", "Sicherheitsaudit",
        "Führt ein Sicherheitsaudit durch und zeigt Ihren Härtungswert",
        "sicherheit;audit;prüfung;härtung;"),
 'fr': ("Contrôle de sécurité", "Audit de sécurité",
        "Lance un audit de sécurité et affiche votre indice de durcissement",
        "sécurité;audit;contrôle;durcissement;"),
 'es': ("Revisión de seguridad", "Auditoría de seguridad",
        "Ejecuta una auditoría de seguridad y muestra tu índice de fortalecimiento",
        "seguridad;auditoría;revisión;fortalecimiento;"),
 'pt_BR': ("Verificação de segurança", "Auditoria de segurança",
        "Executa uma auditoria de segurança e mostra o seu índice de proteção",
        "segurança;auditoria;verificação;proteção;"),
 'it': ("Controllo di sicurezza", "Analisi di sicurezza",
        "Esegue un'analisi di sicurezza e mostra il tuo indice di irrobustimento",
        "sicurezza;analisi;controllo;irrobustimento;"),
}
D['dagric-usb-protect'] = {
 'de': ("USB-Schutz", "Unbekannte USB-Geräte blockieren",
        "Schaltet den USB-Geräteschutz ein oder aus, damit ein unbekannter USB-Stick nicht hinter Ihrem Rücken auf diesem PC handeln kann",
        "usb;schutz;blockieren;sperren;anschluss;gerät;stick;sicherheit;"),
 'fr': ("Protection USB", "Bloquer les périphériques USB inconnus",
        "Active ou désactive la protection des périphériques USB, pour qu'une clé USB inconnue ne puisse rien faire sur ce PC à votre insu",
        "usb;protection;bloquer;verrouillage;port;périphérique;clé;sécurité;"),
 'es': ("Protección USB", "Bloquear dispositivos USB desconocidos",
        "Activa o desactiva la protección de dispositivos USB, para que una memoria USB desconocida no pueda actuar en este PC a tus espaldas",
        "usb;protección;bloquear;bloqueo;puerto;dispositivo;memoria;seguridad;"),
 'pt_BR': ("Proteção USB", "Bloquear dispositivos USB desconhecidos",
        "Liga ou desliga a proteção de dispositivos USB, para que um pendrive desconhecido não possa agir neste PC pelas suas costas",
        "usb;proteção;bloquear;bloqueio;porta;dispositivo;pendrive;segurança;"),
 'it': ("Protezione USB", "Blocca i dispositivi USB sconosciuti",
        "Attiva o disattiva la protezione dei dispositivi USB, così una chiavetta USB sconosciuta non può agire su questo PC alle tue spalle",
        "usb;protezione;bloccare;blocco;porta;dispositivo;chiavetta;sicurezza;"),
}
D['dagric-vm'] = {
 'de': ("Windows in einer virtuellen Maschine", "Ein anderes Betriebssystem im Fenster ausführen (KVM)",
        "Richtet virtuelle Maschinen ein, damit Sie echtes Windows in einem Fenster ausführen können, abgeschottet von Ihren Dateien",
        "vm;virtuelle maschine;windows;emulator;gast;"),
 'fr': ("Windows dans une machine virtuelle", "Exécuter un autre système dans une fenêtre (KVM)",
        "Configure les machines virtuelles pour exécuter un vrai Windows dans une fenêtre, isolé de vos fichiers",
        "vm;machine virtuelle;windows;émulateur;invité;"),
 'es': ("Windows en una máquina virtual", "Ejecutar otro sistema en una ventana (KVM)",
        "Configura máquinas virtuales para poder ejecutar Windows de verdad en una ventana, aislado de tus archivos",
        "vm;máquina virtual;windows;emulador;invitado;"),
 'pt_BR': ("Windows numa máquina virtual", "Rodar outro sistema numa janela (KVM)",
        "Configura máquinas virtuais para você rodar o Windows de verdade numa janela, isolado dos seus arquivos",
        "vm;máquina virtual;windows;emulador;convidado;"),
 'it': ("Windows in una macchina virtuale", "Esegui un altro sistema in una finestra (KVM)",
        "Configura le macchine virtuali per eseguire Windows vero in una finestra, isolato dai tuoi file",
        "vm;macchina virtuale;windows;emulatore;ospite;"),
}
D['dagric-ai'] = {
 'de': ("Lokale KI installieren", "KI-Modelle auf diesem PC ausführen (Ollama)",
        "Installiert Ollama, um KI-Sprachmodelle vollständig auf Ihrer eigenen Hardware auszuführen — funktioniert offline, es wird nichts verschickt",
        "ki;lokale ki;offline ki;assistent;modell;sprachmodell;installieren;"),
 'fr': ("Installer l'IA locale", "Exécuter des modèles d'IA sur ce PC (Ollama)",
        "Installe Ollama pour exécuter des modèles de langage IA entièrement sur votre propre matériel — fonctionne hors ligne, rien n'est envoyé",
        "ia;ia locale;ia hors ligne;assistant;modèle;modèle de langage;installer;"),
 'es': ("Instalar IA local", "Ejecutar modelos de IA en este PC (Ollama)",
        "Instala Ollama para ejecutar modelos de lenguaje de IA por completo en tu propio hardware: funciona sin conexión y no se envía nada",
        "ia;ia local;ia sin conexión;asistente;modelo;modelo de lenguaje;instalar;"),
 'pt_BR': ("Instalar IA local", "Rodar modelos de IA neste PC (Ollama)",
        "Instala o Ollama para rodar modelos de linguagem de IA inteiramente no seu próprio hardware — funciona offline e nada é enviado",
        "ia;ia local;ia offline;assistente;modelo;modelo de linguagem;instalar;"),
 'it': ("Installa IA locale", "Esegui modelli di IA su questo PC (Ollama)",
        "Installa Ollama per eseguire modelli linguistici di IA interamente sul tuo hardware — funziona offline e non viene inviato nulla",
        "ia;ia locale;ia offline;assistente;modello;modello linguistico;installare;"),
}
D['dagric-get-steam'] = {
 'de': ("Steam installieren", "Valves Spiele-Shop",
        "Installiert Steam, Valves Spiele-Shop und -Launcher. Nicht vorinstalliert — die Lizenz verbietet das Beilegen.",
        "spiele;shop;installieren;"),
 'fr': ("Installer Steam", "La boutique de jeux de Valve",
        "Installe Steam, la boutique et le lanceur de jeux de Valve. Non préinstallé — sa licence en interdit l'inclusion.",
        "jeux;boutique;installer;"),
 'es': ("Instalar Steam", "La tienda de juegos de Valve",
        "Instala Steam, la tienda y el lanzador de juegos de Valve. No viene preinstalado: su licencia prohíbe incluirlo.",
        "juegos;tienda;instalar;"),
 'pt_BR': ("Instalar o Steam", "A loja de jogos da Valve",
        "Instala o Steam, a loja e o lançador de jogos da Valve. Não vem pré-instalado — a licença dele proíbe a inclusão.",
        "jogos;loja;instalar;"),
 'it': ("Installa Steam", "Il negozio di giochi di Valve",
        "Installa Steam, il negozio e il launcher di giochi di Valve. Non preinstallato — la sua licenza ne vieta l'inclusione.",
        "giochi;negozio;installare;"),
}
D['dagric-get-heroic'] = {
 'de': ("Heroic Games Launcher installieren", "Spiele von Epic, GOG und Amazon",
        "Installiert Heroic, den quelloffenen Launcher für Spiele von Epic Games, GOG und Amazon Prime",
        "spiele;launcher;shop;installieren;"),
 'fr': ("Installer Heroic Games Launcher", "Jeux Epic, GOG et Amazon",
        "Installe Heroic, le lanceur libre pour les jeux Epic Games, GOG et Amazon Prime",
        "jeux;lanceur;boutique;installer;"),
 'es': ("Instalar Heroic Games Launcher", "Juegos de Epic, GOG y Amazon",
        "Instala Heroic, el lanzador de código abierto para los juegos de Epic Games, GOG y Amazon Prime",
        "juegos;lanzador;tienda;instalar;"),
 'pt_BR': ("Instalar o Heroic Games Launcher", "Jogos da Epic, GOG e Amazon",
        "Instala o Heroic, o lançador de código aberto para os jogos da Epic Games, GOG e Amazon Prime",
        "jogos;lançador;loja;instalar;"),
 'it': ("Installa Heroic Games Launcher", "Giochi Epic, GOG e Amazon",
        "Installa Heroic, il launcher open source per i giochi di Epic Games, GOG e Amazon Prime",
        "giochi;launcher;negozio;installare;"),
}
D['dagric-get-protonup'] = {
 'de': ("ProtonUp-Qt installieren", "Proton- und Wine-Versionen verwalten",
        "Installiert ProtonUp-Qt, um Proton-GE- und Wine-Builds für Steam und Lutris hinzuzufügen und zu aktualisieren",
        "spiele;kompatibilität;installieren;"),
 'fr': ("Installer ProtonUp-Qt", "Gérer les versions de Proton et Wine",
        "Installe ProtonUp-Qt pour ajouter et mettre à jour les versions Proton-GE et Wine pour Steam et Lutris",
        "jeux;compatibilité;installer;"),
 'es': ("Instalar ProtonUp-Qt", "Gestionar versiones de Proton y Wine",
        "Instala ProtonUp-Qt para añadir y actualizar las versiones de Proton-GE y Wine para Steam y Lutris",
        "juegos;compatibilidad;instalar;"),
 'pt_BR': ("Instalar o ProtonUp-Qt", "Gerenciar versões do Proton e do Wine",
        "Instala o ProtonUp-Qt para adicionar e atualizar versões do Proton-GE e do Wine para Steam e Lutris",
        "jogos;compatibilidade;instalar;"),
 'it': ("Installa ProtonUp-Qt", "Gestisci le versioni di Proton e Wine",
        "Installa ProtonUp-Qt per aggiungere e aggiornare le versioni di Proton-GE e Wine per Steam e Lutris",
        "giochi;compatibilità;installare;"),
}
D['dagric-get-bottles'] = {
 'de': ("Bottles installieren", "Windows-Programme ausführen",
        "Installiert Bottles, einen freundlichen Weg, Windows-Programme in eigenständigen, sauber getrennten Umgebungen auszuführen",
        "windows;programme;ausführen;kompatibilität;installieren;"),
 'fr': ("Installer Bottles", "Exécuter des programmes Windows",
        "Installe Bottles, une manière conviviale d'exécuter des programmes Windows dans des environnements indépendants par application",
        "windows;programmes;exécuter;compatibilité;installer;"),
 'es': ("Instalar Bottles", "Ejecutar programas de Windows",
        "Instala Bottles, una forma sencilla de ejecutar programas de Windows en entornos independientes para cada aplicación",
        "windows;programas;ejecutar;compatibilidad;instalar;"),
 'pt_BR': ("Instalar o Bottles", "Executar programas do Windows",
        "Instala o Bottles, um jeito amigável de executar programas do Windows em ambientes independentes por aplicativo",
        "windows;programas;executar;compatibilidade;instalar;"),
 'it': ("Installa Bottles", "Esegui programmi Windows",
        "Installa Bottles, un modo semplice per eseguire programmi Windows in ambienti indipendenti per ciascuna applicazione",
        "windows;programmi;eseguire;compatibilità;installare;"),
}
D['dagric-get-onlyoffice'] = {
 'de': ("ONLYOFFICE installieren", "Office-Paket mit der Formatierung von Microsoft",
        "Installiert ONLYOFFICE, ein Office-Paket, das Word-, Excel- und PowerPoint-Dateien mit sehr genauem Layout öffnet",
        "büro;dokumente;tabelle;präsentation;installieren;"),
 'fr': ("Installer ONLYOFFICE", "Suite bureautique fidèle à la mise en forme Microsoft",
        "Installe ONLYOFFICE, une suite bureautique qui ouvre les fichiers Word, Excel et PowerPoint en respectant très bien la mise en page",
        "bureautique;documents;tableur;présentation;installer;"),
 'es': ("Instalar ONLYOFFICE", "Suite ofimática fiel al formato de Microsoft",
        "Instala ONLYOFFICE, una suite ofimática que abre archivos de Word, Excel y PowerPoint respetando muy bien la maquetación",
        "ofimática;documentos;hoja de cálculo;presentación;instalar;"),
 'pt_BR': ("Instalar o ONLYOFFICE", "Pacote de escritório fiel à formatação da Microsoft",
        "Instala o ONLYOFFICE, um pacote de escritório que abre arquivos do Word, Excel e PowerPoint com fidelidade de layout muito boa",
        "escritório;documentos;planilha;apresentação;instalar;"),
 'it': ("Installa ONLYOFFICE", "Suite per ufficio fedele alla formattazione Microsoft",
        "Installa ONLYOFFICE, una suite per ufficio che apre i file Word, Excel e PowerPoint rispettando molto bene l'impaginazione",
        "ufficio;documenti;foglio di calcolo;presentazione;installare;"),
}
D['dagric-get-joplin'] = {
 'de': ("Joplin installieren", "Private Notizen und Aufgabenlisten",
        "Installiert Joplin, ein quelloffenes Notizbuch mit Ende-zu-Ende-verschlüsselter Synchronisierung zwischen Ihren Geräten",
        "notizen;notizbuch;aufgaben;tagebuch;installieren;"),
 'fr': ("Installer Joplin", "Notes et listes de tâches privées",
        "Installe Joplin, un carnet de notes libre avec synchronisation chiffrée de bout en bout entre vos appareils",
        "notes;carnet;tâches;journal;installer;"),
 'es': ("Instalar Joplin", "Notas y listas de tareas privadas",
        "Instala Joplin, un cuaderno de notas de código abierto con sincronización cifrada de extremo a extremo entre tus dispositivos",
        "notas;cuaderno;tareas;diario;instalar;"),
 'pt_BR': ("Instalar o Joplin", "Notas e listas de tarefas privadas",
        "Instala o Joplin, um caderno de notas de código aberto com sincronização criptografada de ponta a ponta entre seus dispositivos",
        "notas;caderno;tarefas;diário;instalar;"),
 'it': ("Installa Joplin", "Note e liste di cose da fare private",
        "Installa Joplin, un taccuino open source con sincronizzazione cifrata end-to-end tra i tuoi dispositivi",
        "note;taccuino;attività;diario;installare;"),
}
D['dagric-get-localsend'] = {
 'de': ("LocalSend installieren", "Dateien an Geräte in der Nähe senden",
        "Installiert LocalSend, um Dateien zwischen diesem PC und Ihrem Telefon über Ihr eigenes Netzwerk zu bewegen — ohne Cloud, ohne Konto",
        "senden;teilen;übertragen;dateien;telefon;wlan;installieren;"),
 'fr': ("Installer LocalSend", "Envoyer des fichiers aux appareils proches",
        "Installe LocalSend pour déplacer des fichiers entre ce PC et votre téléphone sur votre propre réseau — sans cloud, sans compte",
        "envoyer;partager;transférer;fichiers;téléphone;wifi;installer;"),
 'es': ("Instalar LocalSend", "Enviar archivos a dispositivos cercanos",
        "Instala LocalSend para mover archivos entre este PC y tu móvil por tu propia red: sin nube y sin cuenta",
        "enviar;compartir;transferir;archivos;móvil;wifi;instalar;"),
 'pt_BR': ("Instalar o LocalSend", "Enviar arquivos para dispositivos próximos",
        "Instala o LocalSend para mover arquivos entre este PC e o seu celular pela sua própria rede — sem nuvem e sem conta",
        "enviar;compartilhar;transferir;arquivos;celular;wi-fi;instalar;"),
 'it': ("Installa LocalSend", "Invia file ai dispositivi vicini",
        "Installa LocalSend per spostare file tra questo PC e il tuo telefono sulla tua rete — senza cloud e senza account",
        "inviare;condividere;trasferire;file;telefono;wi-fi;installare;"),
}
D['dagric-get-cryptomator'] = {
 'de': ("Cryptomator installieren", "Dateien verschlüsseln, bevor sie in die Cloud gehen",
        "Installiert Cryptomator, um einen Ordner zu verschlüsseln, damit Dropbox, Google Drive oder OneDrive nur unlesbare Dateien speichern",
        "verschlüsseln;verschlüsselung;tresor;cloud;datenschutz;installieren;"),
 'fr': ("Installer Cryptomator", "Chiffrer les fichiers avant le cloud",
        "Installe Cryptomator pour chiffrer un dossier, afin que Dropbox, Google Drive ou OneDrive ne stockent que des fichiers brouillés",
        "chiffrer;chiffrement;coffre;cloud;confidentialité;installer;"),
 'es': ("Instalar Cryptomator", "Cifrar archivos antes de que lleguen a la nube",
        "Instala Cryptomator para cifrar una carpeta, de forma que Dropbox, Google Drive o OneDrive solo guarden archivos ilegibles",
        "cifrar;cifrado;caja fuerte;nube;privacidad;instalar;"),
 'pt_BR': ("Instalar o Cryptomator", "Criptografar arquivos antes de chegarem à nuvem",
        "Instala o Cryptomator para criptografar uma pasta, de modo que Dropbox, Google Drive ou OneDrive só guardem arquivos embaralhados",
        "criptografar;criptografia;cofre;nuvem;privacidade;instalar;"),
 'it': ("Installa Cryptomator", "Cifra i file prima che arrivino nel cloud",
        "Installa Cryptomator per cifrare una cartella, così Dropbox, Google Drive o OneDrive conservano solo file illeggibili",
        "cifrare;cifratura;cassaforte;cloud;privacy;installare;"),
}
D['dagric-get-upscayl'] = {
 'de': ("Upscayl installieren", "Fotos mit KI vergrößern",
        "Installiert Upscayl, um Fotos mit KI zu vergrößern und zu schärfen, vollständig auf diesem Computer",
        "vergrößern;hochskalieren;schärfen;bild;foto;installieren;"),
 'fr': ("Installer Upscayl", "Agrandir les photos avec l'IA",
        "Installe Upscayl pour agrandir et affiner des photos grâce à l'IA, entièrement sur cet ordinateur",
        "agrandir;mise à l'échelle;affiner;image;photo;installer;"),
 'es': ("Instalar Upscayl", "Ampliar fotos con IA",
        "Instala Upscayl para ampliar y afinar fotos con IA, por completo en este ordenador",
        "ampliar;escalar;afinar;imagen;foto;instalar;"),
 'pt_BR': ("Instalar o Upscayl", "Ampliar fotos com IA",
        "Instala o Upscayl para ampliar e dar nitidez a fotos usando IA, inteiramente neste computador",
        "ampliar;escalar;nitidez;imagem;foto;instalar;"),
 'it': ("Installa Upscayl", "Ingrandisci le foto con l'IA",
        "Installa Upscayl per ingrandire e rendere più nitide le foto con l'IA, interamente su questo computer",
        "ingrandire;ridimensionare;nitidezza;immagine;foto;installare;"),
}
D['dagric-get-resolve'] = {
 'de': ("DaVinci Resolve installieren", "Professioneller Videoeditor",
        "Geführte Installation von DaVinci Resolve, Blackmagics professionellem Videoeditor. Nie beigelegt — mit Ihrer Zustimmung von Blackmagic geladen.",
        "video;schnitt;bearbeiten;farbkorrektur;installieren;"),
 'fr': ("Installer DaVinci Resolve", "Éditeur vidéo professionnel",
        "Installation guidée de DaVinci Resolve, l'éditeur vidéo professionnel de Blackmagic. Jamais fourni — téléchargé chez Blackmagic avec votre accord.",
        "vidéo;montage;éditer;étalonnage;installer;"),
 'es': ("Instalar DaVinci Resolve", "Editor de vídeo profesional",
        "Instalación guiada de DaVinci Resolve, el editor de vídeo profesional de Blackmagic. Nunca se incluye: se descarga de Blackmagic con tu consentimiento.",
        "vídeo;edición;editar;etalonaje;instalar;"),
 'pt_BR': ("Instalar o DaVinci Resolve", "Editor de vídeo profissional",
        "Instalação guiada do DaVinci Resolve, o editor de vídeo profissional da Blackmagic. Nunca é incluído — é baixado da Blackmagic com o seu consentimento.",
        "vídeo;edição;editar;correção de cor;instalar;"),
 'it': ("Installa DaVinci Resolve", "Editor video professionale",
        "Installazione guidata di DaVinci Resolve, l'editor video professionale di Blackmagic. Mai incluso — viene scaricato da Blackmagic con il tuo consenso.",
        "video;montaggio;modificare;correzione colore;installare;"),
}
D['dagric-gaming'] = {
 'de': ("Spiele-Einrichtung", "Proton-GE für Steam",
        "Fügt Steam den Community-Build Proton-GE hinzu, für bessere Spielekompatibilität",
        "spiele;proton;kompatibilität;leistung;"),
 'fr': ("Configuration des jeux", "Proton-GE pour Steam",
        "Ajoute à Steam la version communautaire Proton-GE, pour une meilleure compatibilité des jeux",
        "jeux;proton;compatibilité;performances;"),
 'es': ("Configuración de juegos", "Proton-GE para Steam",
        "Añade a Steam la versión comunitaria Proton-GE, para una mejor compatibilidad de los juegos",
        "juegos;proton;compatibilidad;rendimiento;"),
 'pt_BR': ("Configuração de jogos", "Proton-GE para o Steam",
        "Adiciona ao Steam a versão comunitária Proton-GE, para melhor compatibilidade dos jogos",
        "jogos;proton;compatibilidade;desempenho;"),
 'it': ("Configurazione giochi", "Proton-GE per Steam",
        "Aggiunge a Steam la build della community Proton-GE, per una migliore compatibilità dei giochi",
        "giochi;proton;compatibilità;prestazioni;"),
}
D['dagric-update'] = {
 'de': ("Dagric-Aktualisierung", "Dagric aktuell halten",
        "Signierte Dagric- und Systemaktualisierungen sicher installieren, ohne neu zu installieren",
        "aktualisierung;upgrade;neueste version;system;sicherheit;pakete;"),
 'fr': ("Mise à jour Dagric", "Garder Dagric à jour",
        "Installer en toute sécurité les mises à jour signées de Dagric et du système sans réinstaller",
        "mise à jour;mise a niveau;dernière version;système;sécurité;paquets;"),
 'es': ("Actualización de Dagric", "Mantener Dagric actualizado",
        "Instala de forma segura actualizaciones firmadas de Dagric y del sistema sin reinstalar",
        "actualización;actualizar;última versión;sistema;seguridad;paquetes;"),
 'pt_BR': ("Atualização do Dagric", "Manter o Dagric atualizado",
        "Instala com segurança atualizações assinadas do Dagric e do sistema sem reinstalar",
        "atualização;atualizar;versão mais recente;sistema;segurança;pacotes;"),
 'it': ("Aggiornamento Dagric", "Mantieni Dagric aggiornato",
        "Installa in sicurezza gli aggiornamenti firmati di Dagric e del sistema senza reinstallare",
        "aggiornamento;aggiornare;ultima versione;sistema;sicurezza;pacchetti;"),
}
D['dagric-get-variety'] = {
 'de': ("Rotierende Hintergrundbilder (Variety)", "Automatischer Hintergrundbildwechsel",
        "Installiert Variety, um Ihr Hintergrundbild nach Zeitplan zu wechseln (optional, nicht vorinstalliert)",
        "hintergrundbild;diaschau;wechsel;"),
 'fr': ("Fonds d'écran tournants (Variety)", "Changement automatique de fond d'écran",
        "Installe Variety pour changer votre fond d'écran selon un horaire (facultatif, non préinstallé)",
        "fond d'écran;diaporama;changement;"),
 'es': ("Fondos de pantalla rotativos (Variety)", "Cambio automático de fondo de pantalla",
        "Instala Variety para cambiar tu fondo de pantalla según un horario (opcional, no preinstalado)",
        "fondo de pantalla;presentación;cambio;"),
 'pt_BR': ("Papéis de parede rotativos (Variety)", "Troca automática de papel de parede",
        "Instala o Variety para trocar seu papel de parede em intervalos definidos (opcional, não vem pré-instalado)",
        "papel de parede;apresentação;troca;"),
 'it': ("Sfondi a rotazione (Variety)", "Cambio automatico dello sfondo",
        "Installa Variety per cambiare lo sfondo a intervalli regolari (facoltativo, non preinstallato)",
        "sfondo;presentazione;cambio;"),
}

D['dagric-rewind'] = {
 'de': ("Dagric Rewind", "Systemänderungen rückgängig machen",
        "Systemänderungen ansehen und rückgängig machen, ohne den Bildschirm aufzuzeichnen",
        "rückgängig;wiederherstellen;schnappschuss;prüfpunkt;verlauf;rettung;"),
 'fr': ("Dagric Rewind", "Annulation du système",
        "Voir et inverser les changements du système sans enregistrer votre écran",
        "annuler;restaurer;instantané;point de contrôle;historique;récupération;"),
 'es': ("Dagric Rewind", "Deshacer cambios del sistema",
        "Ver y revertir cambios del sistema sin grabar la pantalla",
        "deshacer;restaurar;instantánea;punto de control;historial;recuperación;"),
 'pt_BR': ("Dagric Rewind", "Desfazer alterações do sistema",
        "Veja e reverta alterações do sistema sem gravar a sua tela",
        "desfazer;restaurar;instantâneo;ponto de restauração;histórico;recuperação;"),
 'it': ("Dagric Rewind", "Annullamento delle modifiche di sistema",
        "Visualizza e annulla le modifiche di sistema senza registrare lo schermo",
        "annullare;ripristinare;istantanea;punto di controllo;cronologia;recupero;"),
}

D['dagric-blueprint'] = {
 'de': ("Dagric Blueprint", "Reproduzierbare Systemkonfiguration",
        "Anwendungen und sichere Einstellungen für den Wiederaufbau dieses Computers ansehen",
        "bauplan;neuinstallation;wiederaufbau;anwendungen;einstellungen;wiederherstellung;export;"),
 'fr': ("Dagric Blueprint", "Configuration système reproductible",
        "Prévisualiser les applications et les réglages sûrs nécessaires pour reconstruire cet ordinateur",
        "plan;réinstallation;reconstruction;applications;réglages;récupération;exportation;"),
 'es': ("Dagric Blueprint", "Configuración reproducible del sistema",
        "Previsualiza las aplicaciones y los ajustes seguros necesarios para reconstruir este ordenador",
        "plano;reinstalar;reconstruir;aplicaciones;ajustes;recuperación;exportar;"),
 'pt_BR': ("Dagric Blueprint", "Configuração reproduzível do sistema",
        "Veja os aplicativos e as configurações seguras necessários para reconstruir este computador",
        "plano;reinstalar;reconstruir;aplicativos;configurações;recuperação;exportar;"),
 'it': ("Dagric Blueprint", "Configurazione di sistema riproducibile",
        "Visualizza le applicazioni e le impostazioni sicure necessarie per ricostruire questo computer",
        "progetto;reinstallare;ricostruire;applicazioni;impostazioni;recupero;esportare;"),
}

D['dagric-life-support'] = {
 'de': ("Dagric Notfallhilfe", "Notfallprüfung des Systems",
        "Prüfen, ob Speicherplatz- oder Ressourcenengpässe eine Wiederherstellung erfordern",
        "wiederherstellung;notfall;speicherplatz;auslastung;zustand;datensicherung;abgesicherter modus;"),
 'fr': ("Assistance vitale Dagric", "Évaluation d'urgence du système",
        "Vérifier si le stockage ou la pression sur les ressources nécessite une récupération",
        "récupération;urgence;stockage;pression;santé;sauvegarde;mode sans échec;"),
 'es': ("Soporte vital de Dagric", "Evaluación de emergencia del sistema",
        "Comprueba si el almacenamiento o la presión de recursos requiere una acción de recuperación",
        "recuperación;emergencia;almacenamiento;presión;salud;copia de seguridad;modo seguro;"),
 'pt_BR': ("Suporte de emergência Dagric", "Avaliação de emergência do sistema",
        "Verifique se o armazenamento ou a pressão de recursos exige uma ação de recuperação",
        "recuperação;emergência;armazenamento;pressão;saúde;backup;modo de segurança;"),
 'it': ("Supporto vitale Dagric", "Valutazione di emergenza del sistema",
        "Controlla se lo spazio o la pressione sulle risorse richiede un'azione di recupero",
        "recupero;emergenza;spazio;pressione;salute;backup;modalità provvisoria;"),
}

D['dagric-support'] = {
 'de': ("Dagric-Supportmodus", "Datenschutzfreundlicher Systembericht",
        "Hardware-, Wiederherstellungs- und Dagric-Änderungsbericht ohne persönliche Daten ansehen",
        "support;diagnose;hardware;systempass;verlauf;wiederherstellung;datenschutz;bericht;"),
 'fr': ("Mode d'assistance Dagric", "Rapport système respectueux de la vie privée",
        "Prévisualiser un rapport sur le matériel, la récupération et les changements Dagric sans données personnelles",
        "assistance;diagnostic;matériel;passeport;historique;récupération;confidentialité;rapport;"),
 'es': ("Modo de soporte de Dagric", "Informe del sistema respetuoso con la privacidad",
        "Previsualiza un informe de hardware, recuperación y cambios de Dagric sin datos personales",
        "soporte;diagnóstico;hardware;pasaporte;historial;recuperación;privacidad;informe;"),
 'pt_BR': ("Modo de suporte Dagric", "Relatório do sistema com privacidade",
        "Veja um relatório de hardware, recuperação e alterações do Dagric sem dados pessoais",
        "suporte;diagnóstico;hardware;passaporte;histórico;recuperação;privacidade;relatório;"),
 'it': ("Modalità assistenza Dagric", "Rapporto di sistema rispettoso della privacy",
        "Visualizza un rapporto su hardware, recupero e modifiche Dagric senza dati personali",
        "assistenza;diagnostica;hardware;passaporto;cronologia;recupero;privacy;rapporto;"),
}

D['dagric-hardware-check'] = {
 'de': ("Diesen PC prüfen", "Hardware-Prüfung",
        "Sehen Sie nach, ob Dagric auf diesem Computer läuft, bevor Sie es installieren",
        "hardware;prüfen;wlan;treiber;grafik;sicherer start;verschlüsselt;festplatte;speicherplatz;kompatibilität;"),
 'fr': ("Vérifier ce PC", "Vérification du matériel",
        "Vérifiez si Dagric fonctionnera sur cet ordinateur, avant de l'installer",
        "matériel;vérifier;wifi;pilote;graphique;démarrage sécurisé;chiffré;disque;espace;compatibilité;"),
 'es': ("Comprobar este PC", "Comprobación del hardware",
        "Comprueba si Dagric funcionará en este ordenador antes de instalarlo",
        "hardware;comprobar;wifi;controlador;gráficos;arranque seguro;cifrado;disco;espacio;compatibilidad;"),
 'pt_BR': ("Verificar este PC", "Verificação de hardware",
        "Veja se o Dagric vai funcionar neste computador, antes de instalar",
        "hardware;verificar;wi-fi;driver;vídeo;inicialização segura;criptografado;disco;espaço;compatibilidade;"),
 'it': ("Controlla questo PC", "Controllo dell'hardware",
        "Verifica se Dagric funzionerà su questo computer, prima di installarlo",
        "hardware;controllo;wi-fi;driver;grafica;avvio sicuro;cifrato;disco;spazio;compatibilità;"),
}

KEYS = ('Name', 'GenericName', 'Comment', 'Keywords')


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read().split('\n')


def base_keywords(lines):
    for ln in lines:
        if ln.startswith('Keywords='):
            return ln[len('Keywords='):]
    return ''


def strip_generated(lines):
    """Drop the block this script wrote last time, so it is idempotent."""
    out, skipping = [], False
    for ln in lines:
        if ln.startswith('# Localised keys below are generated'):
            skipping = True
            continue
        if skipping:
            if ln.startswith('#') or re.match(r'^(Name|GenericName|Comment|Keywords)\[', ln):
                continue
            if ln.strip() == '':
                continue
            skipping = False
        out.append(ln)
    return out


def build(path, entry):
    lines = strip_generated(read(path))
    while lines and lines[-1].strip() == '':
        lines.pop()
    kw = base_keywords(lines)
    block = ['', MARK.rstrip('\n')]
    for key_i, key in enumerate(KEYS):
        for lang in LANGS:
            if lang not in entry:
                continue
            val = entry[lang][key_i]
            if not val:
                continue
            if key == 'Keywords':
                # Additive: the English list first, then the native terms.
                # Never a replacement -- see the header.
                if not kw:
                    continue
                val = kw + val
            block.append('%s[%s]=%s' % (key, lang, val))
    return '\n'.join(lines + block) + '\n'


def main():
    check = '--check' in sys.argv
    bad = 0
    done = 0
    for did, entry in sorted(D.items()):
        path = os.path.join(APPS, did + '.desktop')
        if not os.path.exists(path):
            print('ERROR: %s.desktop does not exist' % did, file=sys.stderr)
            bad = 1
            continue
        want = build(path, entry)
        with open(path, encoding='utf-8') as f:
            have = f.read()
        if have == want:
            done += 1
            continue
        if check:
            print('ERROR: %s.desktop is out of date — run: python3 tools/i18n-desktop.py'
                  % did, file=sys.stderr)
            bad = 1
        else:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(want)
            print('  updated %s.desktop' % did)
            done += 1

    # Every shipped entry must be in the table. A new launcher entry that
    # nobody added here would ship English-only into an otherwise German
    # menu, and nothing else in the build would notice.
    have_files = {f[:-len('.desktop')] for f in os.listdir(APPS) if f.endswith('.desktop')}
    for missing in sorted(have_files - set(D)):
        print('ERROR: %s.desktop has no entry in tools/i18n-desktop.py' % missing,
              file=sys.stderr)
        bad = 1

    print('i18n-desktop: %d entries, %d languages each' % (done, len(LANGS)))
    return bad


if __name__ == '__main__':
    sys.exit(main())
