#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 DGR Operations <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Compile po/*.po into the shipped .mo catalogues, byte-identically to msgfmt.

    python3 tools/i18n-mo.py            compile
    python3 tools/i18n-mo.py --check    verify only, change nothing

WHY THIS EXISTS ALONGSIDE tools/i18n-build.sh
---------------------------------------------
i18n-build.sh is the real tool and stays the real tool. It shells out to GNU
msgfmt, which also runs `-c` (format-specifier and plural-rule validation) that
nothing here reproduces. Use it whenever you are on a machine that has gettext.

This is for the machine that does not. The primary development machine for this
project is Windows with no gettext, no working WSL and no Docker daemon, which
means i18n-build.sh --check — the gate wired into 0150-locales.hook.chroot —
CANNOT BE RUN THERE AT ALL. That gap is not theoretical: a .mo was once
regenerated by hand on that machine, committed, and pushed, and it was wrong in
a way no content-level check could see. Every message decoded correctly and
every translation was right. What differed was the header: the writer dropped
the "POT-Creation-Date:" line, 41 bytes, and msgfmt copies the header msgstr
verbatim. So `msgfmt -c -o $TMP $po && cmp -s $TMP $mo` compared 66042 bytes
against 66083 and failed, and the IMAGE BUILD fails with it.

The lesson is the reason for the design below: the check that matters is not
"does the catalogue contain the right translations", it is "is this the exact
byte string msgfmt would emit". Anything less passes a broken file.

WHAT "BYTE-IDENTICAL" REQUIRES — this is msgfmt's write-mo.c, not an invention
-----------------------------------------------------------------------------
    header 28B | orig table 8n | trans table 8n | hash table 4*hs
    | every original string, NUL-terminated, in sorted order
    | every translation string, NUL-terminated, in the same order

  * entries sorted ascending on the raw bytes of the lookup key
  * hash table size = next_prime(n * 4 / 3), integer division, minimum 3
  * hash = gettext's hash-string.c PJW variant; open addressing with
    incr = 1 + (h % (hs - 2)); stored value is the entry index + 1
  * a msgctxt makes the key  ctxt \\x04 msgid ; plurals join msgid/msgstr
    with \\0
  * fuzzy entries and empty msgstr are DROPPED. That is msgfmt's default and
    the whole safety net: an unreviewed translation is left out so the owner
    sees the English source instead of a machine guess.
  * no padding anywhere — msgfmt packs the string area with alignment 1

Verified against the five catalogues in this tree: recompiling every po/*.po
here reproduces the committed .mo byte for byte.
"""
import glob
import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALEDIR = "config/includes.chroot/usr/share/locale"
DOMAIN = "dagric"

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\",
           "a": "\a", "b": "\b", "f": "\f", "v": "\v"}
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')
DIRECTIVE = re.compile(r"^(msgctxt|msgid_plural|msgid|msgstr\[(\d+)\]|msgstr)\s+(.*)$")


def unescape(s):
    out, i = [], 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            if n in ESCAPES:
                out.append(ESCAPES[n]); i += 2; continue
            if n == "x":
                j = i + 2
                while j < len(s) and s[j] in "0123456789abcdefABCDEF":
                    j += 1
                out.append(chr(int(s[i + 2:j], 16))); i = j; continue
            if n in "01234567":
                j = i + 1
                while j < len(s) and j < i + 4 and s[j] in "01234567":
                    j += 1
                out.append(chr(int(s[i + 1:j], 8))); i = j; continue
        out.append(c); i += 1
    return "".join(out)


def parse_po(path):
    """The (key, value) pairs msgfmt would emit, still escaped."""
    entries, cur, key = [], {}, None

    def flush():
        if not cur:
            return
        # "#~" is a commented-out obsolete entry and "#, fuzzy" is an
        # unreviewed one. msgfmt emits neither without --use-fuzzy, and this
        # must not either or the counts drift and cmp fails.
        if cur.get("obsolete") or cur.get("fuzzy") or cur.get("id") is None:
            cur.clear(); return
        plural = cur.get("plural")
        if plural is not None:
            strs = [cur.get("str%d" % i, "") for i in range(cur.get("nplural", 0))]
            if not strs or all(s == "" for s in strs):
                cur.clear(); return
            k, v = cur["id"] + "\0" + plural, "\0".join(strs)
        else:
            s = cur.get("str")
            if not s:
                cur.clear(); return
            k, v = cur["id"], s
        if cur.get("ctxt") is not None:
            k = cur["ctxt"] + "\x04" + k
        entries.append((k, v))
        cur.clear()

    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n").rstrip()
        if not line.strip():
            flush(); key = None; continue
        if line.startswith("#~"):
            cur["obsolete"] = True; continue
        if line.startswith("#,"):
            if "fuzzy" in line:
                cur["fuzzy"] = True
            continue
        if line.startswith("#"):
            continue
        m = DIRECTIVE.match(line)
        if m:
            kind, idx, rest = m.group(1), m.group(2), m.group(3)
            val = "".join(STRING.findall(rest))
            if kind == "msgid":
                cur["id"] = val; key = "id"
            elif kind == "msgid_plural":
                cur["plural"] = val; key = "plural"
            elif kind == "msgctxt":
                cur["ctxt"] = val; key = "ctxt"
            elif kind == "msgstr":
                cur["str"] = val; key = "str"
            else:
                n = int(idx)
                cur["str%d" % n] = val
                cur["nplural"] = max(cur.get("nplural", 0), n + 1)
                key = "str%d" % n
            continue
        # A continuation line: bare "..." belonging to the previous directive.
        if line.lstrip().startswith('"') and key:
            cur[key] = cur.get(key, "") + "".join(STRING.findall(line))
    flush()
    return [(unescape(k).encode("utf-8"), unescape(v).encode("utf-8"))
            for k, v in entries]


def gnu_hash(bs):
    """gettext's hash-string.c — a PJW hash over the raw key bytes."""
    h = 0
    for c in bs:
        h = ((h << 4) + c) & 0xFFFFFFFF
        g = h & 0xF0000000
        if g:
            h ^= g >> 24
            h ^= g
            h &= 0xFFFFFFFF
    return h


def next_prime(n):
    def is_prime(x):
        if x < 2:
            return False
        i = 2
        while i * i <= x:
            if x % i == 0:
                return False
            i += 1
        return True
    while not is_prime(n):
        n += 1
    return n


def compile_mo(entries):
    entries = sorted(entries, key=lambda e: e[0])
    n = len(entries)
    hs = max(3, next_prime((n * 4) // 3))
    otab_off = 28
    ttab_off = otab_off + 8 * n
    htab_off = ttab_off + 8 * n
    pos = htab_off + 4 * hs

    blob, otab, ttab = bytearray(), [], []
    for k, _ in entries:
        otab.append((len(k), pos)); blob += k + b"\0"; pos += len(k) + 1
    for _, v in entries:
        ttab.append((len(v), pos)); blob += v + b"\0"; pos += len(v) + 1

    htab = [0] * hs
    for j, (k, _) in enumerate(entries):
        h = gnu_hash(k)
        idx, incr = h % hs, 1 + (h % (hs - 2))
        while htab[idx] != 0:
            idx += incr
            if idx >= hs:
                idx -= hs
        htab[idx] = j + 1

    out = bytearray()
    out += struct.pack("<7I", 0x950412DE, 0, n, otab_off, ttab_off, hs, htab_off)
    for length, off in otab:
        out += struct.pack("<2I", length, off)
    for length, off in ttab:
        out += struct.pack("<2I", length, off)
    for v in htab:
        out += struct.pack("<I", v)
    return bytes(out + blob)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    if mode not in ("build", "--check"):
        sys.exit("usage: %s [--check]" % sys.argv[0])
    os.chdir(ROOT)

    pos = sorted(glob.glob("po/*.po"))
    if not pos:
        sys.exit("ERROR: no .po files found in po/ — nothing to compile.")

    fail = 0
    for po in pos:
        lang = os.path.basename(po)[:-3]
        mo = "%s/%s/LC_MESSAGES/%s.mo" % (LOCALEDIR, lang, DOMAIN)
        entries = parse_po(po)
        data = compile_mo(entries)

        if mode == "--check":
            if not os.path.exists(mo) or os.path.getsize(mo) == 0:
                print("ERROR: %s is missing or empty" % mo, file=sys.stderr)
                fail = 1
            elif open(mo, "rb").read() != data:
                print("ERROR: %s does not match %s — run: python3 tools/i18n-mo.py"
                      % (mo, po), file=sys.stderr)
                fail = 1
            else:
                print("  ok      %-6s %d messages, %d bytes" % (lang, len(entries), len(data)))
            continue

        os.makedirs(os.path.dirname(mo), exist_ok=True)
        open(mo, "wb").write(data)
        print("  %-6s %d messages -> %s (%d bytes)" % (lang, len(entries), mo, len(data)))

    if fail:
        sys.exit(1)
    print("\n  %d catalogue(s) %s" % (len(pos),
          "present and byte-identical to msgfmt output" if mode == "--check" else "written"))


if __name__ == "__main__":
    main()
