#!/bin/sh
# SPDX-FileCopyrightText: 2026 IMPRESSIONSDIRECT360 LLC <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Dagric OS — rebuild po/dagric.pot from the source, and merge it into every
# translation. Run this on a Debian machine (or in WSL) after changing any
# user-facing string:
#
#     sh tools/i18n-extract.sh
#
# Needs: gettext (xgettext, msgmerge, msgcat) — a BUILD-HOST package. Nothing
# new ships in the image; gettext-base, which is all the runtime needs, is
# already there.
#
# WHAT IT EXTRACTS, AND THE ONE PART THAT IS NOT OBVIOUS
# ------------------------------------------------------
# xgettext --language=Shell already knows gettext, ngettext, eval_gettext and
# eval_ngettext as keywords, so the tools in usr/bin need no --keyword flags.
#
# What it CANNOT see is a string that arrives at runtime out of a data file:
# the NAME and DESCRIPTION of every .look, .style and .iconstyle, and the Name
# of every wallpaper pack. Those reach the owner through dg_tr() — a lookup on a
# variable — and xgettext cannot follow a variable. So this script reads the
# same data files and writes po/dagric-data-strings.sh, a generated shell file
# whose only purpose is to be a thing xgettext can read. It is committed rather
# than kept in a temp dir so the "#:" source references in the .pot stay stable
# between runs and a diff of the .pot means something.
#
# dagric-hardware-check is in the source list even though it has no gettext()
# calls yet — it was still being written when this was set up. Wiring it in now
# means the day those calls land the strings appear in the .pot with no change
# here. (dagric-hub was in the same position and has since been converted.)
# Leaving a tool out is the failure that goes unnoticed:
# it just stays English inside an otherwise German product, and nothing
# complains. If you add a dagric-* tool, add it here in the same commit.
#
# AND IT IS NOT ONLY /usr/bin. This list was once exactly "the tools", and
# /usr/lib/dagric/display-common.sh — a sourced library, not a tool — shipped
# six user-facing strings that no catalogue ever saw. dg_friendly_name() names
# the owner's monitors ("Built-in screen", "Screen on HDMI") and those names go
# into a kdialog menu AND into the middle of a translated sentence, so French
# read "Taille du texte et des icônes sur Built-in screen (1920 x 1080) :".
# Anything that speaks to the owner belongs here, wherever it lives.
set -e
cd "$(dirname "$0")/.."

BIN=config/includes.chroot/usr/bin
LIB=config/includes.chroot/usr/lib/dagric
SHARE=config/includes.chroot/usr/share
GEN=po/dagric-data-strings.sh

command -v xgettext >/dev/null 2>&1 || {
    echo "xgettext is required: apt install gettext" >&2; exit 1; }

# --- 1. the generated file of data-file strings ------------------------------
#
# The TRANSLATORS: comments are emitted per string, because a translator
# looking at "Focus" or "Dagric Ember" in a list of 200 messages has no way to
# know what it is otherwise. xgettext copies them into the .pot.
{
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# GENERATED by tools/i18n-extract.sh — DO NOT EDIT, DO NOT SHIP.'
    printf '%s\n' '#'
    printf '%s\n' '# This file is never installed and never run. It exists so that xgettext'
    printf '%s\n' '# can see the strings that live in Dagric'"'"'s DATA files — the .look,'
    printf '%s\n' '# .style and .iconstyle drop-ins and the wallpaper packs — which reach'
    printf '%s\n' '# the owner through'
    printf '%s\n' '# dg_tr() at runtime, i.e. through a variable that xgettext cannot follow.'
    printf '%s\n' '#'
    printf '%s\n' '# Regenerate with:  sh tools/i18n-extract.sh'
    printf '%s\n' ''

    # EVERY QML WINDOW'S OWN CHROME, not just the wizard's.
    #
    # Same reason as the drop-in files below: these windows' emit_strings read
    # their sentences from a here-doc and pass each through gettext "$_s", and
    # xgettext cannot follow a variable. Without this block a window is the one
    # part of Dagric that stays in English no matter how many catalogues exist.
    #
    # The list is read straight out of each shell script, between its STRINGS
    # markers, so the two can never drift: adding a sentence there is all that
    # is needed for it to appear here on the next extraction.
    #
    # THE LOOP IS THE FIX. This block named dagric-firstrun and only
    # dagric-firstrun, so when the Family Limits window was written to the same
    # design its 28 sentences reached no catalogue — and every check passed,
    # because a string nobody extracts has no missing translation. Any window
    # added here is covered from its first build. tools/i18n-wizard.py holds the
    # matching list and fails the build if a window's two halves disagree.
    for _win in "$BIN/dagric-firstrun:the setup wizard" \
                "$BIN/dagric-family:the Family Limits window"; do
        _wf=${_win%%:*}
        _wd=${_win#*:}
        [ -f "$_wf" ] || continue
        grep -q "<<'STRINGS'" "$_wf" || {
            echo "extract: $_wf has no STRINGS here-doc — window words not extracted" >&2
            continue
        }
        printf '# TRANSLATORS: %s'"'"'s own buttons, headings and labels.\n' "$_wd"
        printf '# Keep button labels short; they sit in fixed-width buttons beside\n'
        printf '# each other. %%1 and %%2 are values substituted at runtime and may be\n'
        printf '# reordered to suit the language.\n'
        sed -n "/<<'STRINGS'/,/^STRINGS$/p" "$_wf" \
          | sed -e "1d" -e "\$d" \
          | while IFS= read -r line; do
                [ -n "$line" ] || continue
                printf 'gettext "%s"\n' "$(printf '%s' "$line" | sed 's/"/\\"/g')"
            done
        printf '\n'
    done

    for f in "$SHARE"/dagric/looks/*.look; do
        [ -f "$f" ] || continue
        id=${f##*/}; id=${id%.look}
        n=$(sed -n 's/^[[:space:]]*NAME[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        d=$(sed -n 's/^[[:space:]]*DESCRIPTION[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        [ -n "$n" ] && {
            printf '# TRANSLATORS: name of the "%s" taskbar layout in Dagric Looks and the\n' "$id"
            printf '# setup wizard. One or two words, shown as the title of a picture tile.\n'
            printf 'gettext "%s"\n' "$n"
        }
        [ -n "$d" ] && {
            printf '# TRANSLATORS: one-line description of the "%s" taskbar layout, shown\n' "$id"
            printf '# under its name. Keep it short — it has to fit on one line beside a tile.\n'
            printf 'gettext "%s"\n' "$d"
        }
    done

    for f in "$SHARE"/dagric/styles/*.style; do
        [ -f "$f" ] || continue
        id=${f##*/}; id=${id%.style}
        n=$(sed -n 's/^[[:space:]]*NAME[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        d=$(sed -n 's/^[[:space:]]*DESCRIPTION[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        [ -n "$n" ] && {
            printf '# TRANSLATORS: name of the "%s" desktop style (colours, wallpaper and\n' "$id"
            printf '# effects) in Dagric Styles and the appearance gallery. One or two words.\n'
            printf 'gettext "%s"\n' "$n"
        }
        [ -n "$d" ] && {
            printf '# TRANSLATORS: one-line description of the "%s" desktop style, shown\n' "$id"
            printf '# under its name. Keep it short.\n'
            printf 'gettext "%s"\n' "$d"
        }
    done

    for f in "$SHARE"/dagric/icon-styles/*.iconstyle; do
        [ -f "$f" ] || continue
        id=${f##*/}; id=${id%.iconstyle}
        n=$(sed -n 's/^[[:space:]]*NAME[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        d=$(sed -n 's/^[[:space:]]*DESCRIPTION[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        [ -n "$n" ] && {
            printf '# TRANSLATORS: name of the "%s" icon family in Dagric Appearance.\n' "$id"
            printf '# One or two words, shown as the title of a picture tile.\n'
            printf 'gettext "%s"\n' "$n"
        }
        [ -n "$d" ] && {
            printf '# TRANSLATORS: one-line description of the "%s" icon family, shown\n' "$id"
            printf '# under its name. Keep it short.\n'
            printf 'gettext "%s"\n' "$d"
        }
    done

    for f in "$SHARE"/wallpapers/*/metadata.json; do
        [ -f "$f" ] || continue
        n=$(sed -n 's/.*"Name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$f" | head -1)
        [ -n "$n" ] || continue
        printf '# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand\n'
        printf '# and never changes; translate only the descriptive word after it.\n'
        printf 'gettext "%s"\n' "$n"
    done
} > "$GEN"

# --- 2. extract ---------------------------------------------------------------
# --add-comments=TRANSLATORS: carries the notes above each call into the .pot.
# Without it a translator sees "y yes" and "Documents" with no context at all,
# which is how "Documents" ends up translated as a verb.
# THE SOURCE LIST IS DERIVED, BECAUSE THE HAND-WRITTEN ONE FAILED SILENTLY.
#
# This used to be thirty-one paths typed out by hand. dagric-upgrade-to-pro —
# the tool that takes somebody's $39 and turns their machine into a Pro one —
# was not among them. That did not matter while the file had no gettext calls,
# and became the whole problem the moment it got 91 of them: xgettext was never
# shown the file, not one msgid reached the .pot, `msgmerge` reported every
# catalogue as 100% translated, and the paid upgrade path would have shipped in
# English with every check in this repo saying it was fine. The failure mode of
# a hand-maintained list is not a build error, it is a quiet nothing.
#
# So the list is now computed the same way tools/build-pro-assets.sh computes
# the Pro bundle, and for the reason its header gives: "A hardcoded list would
# have been shorter and would have been wrong within a month."
#
# EVERY file in $BIN is passed, not only the ones that currently call gettext.
# xgettext contributes nothing for a file with no keywords in it, so the cost of
# including one is zero — while the cost of EXCLUDING one is the bug above.
# That also preserves the property the old list had deliberately: a tool with no
# gettext calls yet (dagric-hardware-check was listed for exactly that reason)
# stays wired in, so its first translated string works without anyone
# remembering this file exists.
#
# `sort` keeps the "#:" source references stable between runs, so a diff of the
# .pot still means something.
# $LIB IS DERIVED TOO NOW, for the reason the paragraph above gives about $BIN.
#
# It was a hand-typed pair — display-common.sh and display-autoscale — and
# /usr/lib/dagric/family-apply was added with twelve gettext calls and correct
# TEXTDOMAIN wiring that this list never picked up. Every check in the repo
# reported success, because a file nobody extracts from has no missing strings.
# The header two paragraphs up already says it: "AND IT IS NOT ONLY /usr/bin ...
# Anything that speaks to the owner belongs here, wherever it lives." That was
# true of the prose and not of the code.
#
# __pycache__ is a directory and is skipped by the -f test; .pyc files would be
# skipped anyway as unparseable, but they should never be in the tree at all
# (packages/stage-packages.sh now strips them).
set -- "$GEN"
_nlib=0
for _f in $(ls "$LIB" | sort); do
    [ -f "$LIB/$_f" ] || continue
    case "$_f" in *.pyc) continue ;; esac
    set -- "$@" "$LIB/$_f"
    _nlib=$((_nlib + 1))
done
_nbin=0
for _f in $(ls "$BIN" | sort); do
    [ -f "$BIN/$_f" ] || continue
    set -- "$@" "$BIN/$_f"
    _nbin=$((_nbin + 1))
done
echo "extract: $_nbin files from $BIN, plus $_nlib from $LIB and the generated data strings"

# --add-comments=TRANSLATORS: carries the notes above each call into the .pot.
# Without it a translator sees "y yes" and "Documents" with no context at all,
# which is how "Documents" ends up translated as a verb.
xgettext \
    --language=Shell \
    --from-code=UTF-8 \
    --add-comments=TRANSLATORS: \
    --package-name=dagric \
    --package-version=1.0 \
    --msgid-bugs-address=repo@dagric.com \
    --copyright-holder='IMPRESSIONSDIRECT360 LLC' \
    -o po/dagric.pot \
    "$@"

echo "po/dagric.pot: $(grep -c '^msgid ' po/dagric.pot) messages (including the header)"

# --- 3. merge into every existing translation --------------------------------
# --backup=none: a po/de.po~ left behind would be picked up by the *.po glob in
# tools/i18n-build.sh on some shells and compiled into a locale called "de.po~".
for po in po/*.po; do
    [ -f "$po" ] || continue
    msgmerge --quiet --update --backup=none "$po" po/dagric.pot
    printf '  merged %-12s ' "${po##*/}"
    msgfmt --statistics -o /dev/null "$po" 2>&1 | tr -d '\n'
    printf '\n'
done
