#!/bin/sh
# SPDX-FileCopyrightText: 2026 DGR Operations <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Dagric OS — rebuild po/dagric.pot from the source, and merge it into every
# translation. Run this on a Debian machine (or in WSL) after changing any
# user-facing string:
#
#     sh tools/i18n-extract.sh
#
# Needs: gettext (xgettext, msgmerge, msgcat) — a BUILD-HOST package. Nothing
# new ships in the image; gettext-base, which is all the runtime needs, is
# already there.
#
# WHAT IT EXTRACTS, AND THE ONE PART THAT IS NOT OBVIOUS
# ------------------------------------------------------
# xgettext --language=Shell already knows gettext, ngettext, eval_gettext and
# eval_ngettext as keywords, so the tools in usr/bin need no --keyword flags.
#
# What it CANNOT see is a string that arrives at runtime out of a data file:
# the NAME and DESCRIPTION of every .look and .style, and the Name of every
# wallpaper pack. Those reach the owner through dg_tr() — a lookup on a
# variable — and xgettext cannot follow a variable. So this script reads the
# same data files and writes po/dagric-data-strings.sh, a generated shell file
# whose only purpose is to be a thing xgettext can read. It is committed rather
# than kept in a temp dir so the "#:" source references in the .pot stay stable
# between runs and a diff of the .pot means something.
#
# dagric-hardware-check is in the source list even though it has no gettext()
# calls yet — it was still being written when this was set up. Wiring it in now
# means the day those calls land the strings appear in the .pot with no change
# here. (dagric-hub was in the same position and has since been converted.)
# Leaving a tool out is the failure that goes unnoticed:
# it just stays English inside an otherwise German product, and nothing
# complains. If you add a dagric-* tool, add it here in the same commit.
#
# AND IT IS NOT ONLY /usr/bin. This list was once exactly "the tools", and
# /usr/lib/dagric/display-common.sh — a sourced library, not a tool — shipped
# six user-facing strings that no catalogue ever saw. dg_friendly_name() names
# the owner's monitors ("Built-in screen", "Screen on HDMI") and those names go
# into a kdialog menu AND into the middle of a translated sentence, so French
# read "Taille du texte et des icônes sur Built-in screen (1920 x 1080) :".
# Anything that speaks to the owner belongs here, wherever it lives.
set -e
cd "$(dirname "$0")/.."

BIN=config/includes.chroot/usr/bin
LIB=config/includes.chroot/usr/lib/dagric
SHARE=config/includes.chroot/usr/share
GEN=po/dagric-data-strings.sh

command -v xgettext >/dev/null 2>&1 || {
    echo "xgettext is required: apt install gettext" >&2; exit 1; }

# --- 1. the generated file of data-file strings ------------------------------
#
# The TRANSLATORS: comments are emitted per string, because a translator
# looking at "Focus" or "Dagric Ember" in a list of 200 messages has no way to
# know what it is otherwise. xgettext copies them into the .pot.
{
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# GENERATED by tools/i18n-extract.sh — DO NOT EDIT, DO NOT SHIP.'
    printf '%s\n' '#'
    printf '%s\n' '# This file is never installed and never run. It exists so that xgettext'
    printf '%s\n' '# can see the strings that live in Dagric'"'"'s DATA files — the .look and'
    printf '%s\n' '# .style drop-ins and the wallpaper packs — which reach the owner through'
    printf '%s\n' '# dg_tr() at runtime, i.e. through a variable that xgettext cannot follow.'
    printf '%s\n' '#'
    printf '%s\n' '# Regenerate with:  sh tools/i18n-extract.sh'
    printf '%s\n' ''

    # The first-run wizard's own chrome.
    #
    # Same reason as the drop-in files below: dagric-firstrun's emit_strings
    # reads its sentences from a here-doc and passes each through gettext "$_s",
    # and xgettext cannot follow a variable. Without this block the wizard — the
    # first screen a customer sees — is the one part of Dagric that stays in
    # English no matter how many catalogues exist.
    #
    # The list is read straight out of the shell script, between its STRINGS
    # markers, so the two can never drift: adding a sentence there is all that
    # is needed for it to appear here on the next extraction.
    FIRSTRUN=$BIN/dagric-firstrun
    if [ -f "$FIRSTRUN" ]; then
        printf '# TRANSLATORS: the setup wizard'"'"'s own buttons, headings and step names.\n'
        printf '# This is the first screen a new owner sees. Keep button labels short;\n'
        printf '# they sit in fixed-width buttons beside each other.\n'
        sed -n "/<<'STRINGS'/,/^STRINGS$/p" "$FIRSTRUN" \
          | sed -e "1d" -e "\$d" \
          | while IFS= read -r line; do
                [ -n "$line" ] || continue
                printf 'gettext "%s"\n' "$(printf '%s' "$line" | sed 's/"/\\"/g')"
            done
        printf '\n'
    fi

    for f in "$SHARE"/dagric/looks/*.look; do
        [ -f "$f" ] || continue
        id=${f##*/}; id=${id%.look}
        n=$(sed -n 's/^[[:space:]]*NAME[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        d=$(sed -n 's/^[[:space:]]*DESCRIPTION[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        [ -n "$n" ] && {
            printf '# TRANSLATORS: name of the "%s" taskbar layout in Dagric Looks and the\n' "$id"
            printf '# setup wizard. One or two words, shown as the title of a picture tile.\n'
            printf 'gettext "%s"\n' "$n"
        }
        [ -n "$d" ] && {
            printf '# TRANSLATORS: one-line description of the "%s" taskbar layout, shown\n' "$id"
            printf '# under its name. Keep it short — it has to fit on one line beside a tile.\n'
            printf 'gettext "%s"\n' "$d"
        }
    done

    for f in "$SHARE"/dagric/styles/*.style; do
        [ -f "$f" ] || continue
        id=${f##*/}; id=${id%.style}
        n=$(sed -n 's/^[[:space:]]*NAME[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        d=$(sed -n 's/^[[:space:]]*DESCRIPTION[[:space:]]*=[[:space:]]*//p' "$f" | head -1 | sed 's/[[:space:]]*$//')
        [ -n "$n" ] && {
            printf '# TRANSLATORS: name of the "%s" desktop style (colours, wallpaper and\n' "$id"
            printf '# effects) in Dagric Styles and the appearance gallery. One or two words.\n'
            printf 'gettext "%s"\n' "$n"
        }
        [ -n "$d" ] && {
            printf '# TRANSLATORS: one-line description of the "%s" desktop style, shown\n' "$id"
            printf '# under its name. Keep it short.\n'
            printf 'gettext "%s"\n' "$d"
        }
    done

    for f in "$SHARE"/wallpapers/*/metadata.json; do
        [ -f "$f" ] || continue
        n=$(sed -n 's/.*"Name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$f" | head -1)
        [ -n "$n" ] || continue
        printf '# TRANSLATORS: the name of a Dagric wallpaper pack. "Dagric" is the brand\n'
        printf '# and never changes; translate only the descriptive word after it.\n'
        printf 'gettext "%s"\n' "$n"
    done
} > "$GEN"

# --- 2. extract ---------------------------------------------------------------
# --add-comments=TRANSLATORS: carries the notes above each call into the .pot.
# Without it a translator sees "y yes" and "Documents" with no context at all,
# which is how "Documents" ends up translated as a verb.
xgettext \
    --language=Shell \
    --from-code=UTF-8 \
    --add-comments=TRANSLATORS: \
    --package-name=dagric \
    --package-version=1.0 \
    --msgid-bugs-address=repo@dagric.com \
    --copyright-holder='DGR Operations' \
    -o po/dagric.pot \
    "$GEN" \
    "$LIB"/display-common.sh \
    "$BIN"/dagric-i18n.sh \
    "$BIN"/dagric-ai \
    "$BIN"/dagric-appearance \
    "$BIN"/dagric-display \
    "$BIN"/dagric-driver-offer \
    "$BIN"/dagric-drivers \
    "$BIN"/dagric-firstrun \
    "$BIN"/dagric-gaming \
    "$BIN"/dagric-get-bottles \
    "$BIN"/dagric-get-cryptomator \
    "$BIN"/dagric-get-heroic \
    "$BIN"/dagric-get-joplin \
    "$BIN"/dagric-get-localsend \
    "$BIN"/dagric-get-onlyoffice \
    "$BIN"/dagric-get-protonup \
    "$BIN"/dagric-get-resolve \
    "$BIN"/dagric-get-steam \
    "$BIN"/dagric-get-upscayl \
    "$BIN"/dagric-get-variety \
    "$BIN"/dagric-guide \
    "$BIN"/dagric-hardware-check \
    "$BIN"/dagric-hub \
    "$BIN"/dagric-looks \
    "$BIN"/dagric-manual \
    "$BIN"/dagric-migrate \
    "$BIN"/dagric-security-checkup \
    "$BIN"/dagric-setup \
    "$BIN"/dagric-style \
    "$BIN"/dagric-usb-protect \
    "$BIN"/dagric-vm \
    "$BIN"/dagric-welcome

echo "po/dagric.pot: $(grep -c '^msgid ' po/dagric.pot) messages (including the header)"

# --- 3. merge into every existing translation --------------------------------
# --backup=none: a po/de.po~ left behind would be picked up by the *.po glob in
# tools/i18n-build.sh on some shells and compiled into a locale called "de.po~".
for po in po/*.po; do
    [ -f "$po" ] || continue
    msgmerge --quiet --update --backup=none "$po" po/dagric.pot
    printf '  merged %-12s ' "${po##*/}"
    msgfmt --statistics -o /dev/null "$po" 2>&1 | tr -d '\n'
    printf '\n'
done
