#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 DGR Operations <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Dagric OS -- keep site/sitemap.xml's hand-written entries honest.
#
#     python3 tools/sitemap.py           rewrite lastmod from git, add missing pages
#     python3 tools/sitemap.py --check   report drift and fail; change nothing
#
# WHY THIS EXISTS
# ---------------
# sitemap.xml's own header says it: "STILL A MANUAL STEP, AND THAT IS THE OPEN
# RISK... they have now drifted twice. The durable fix is to generate them from
# git the same way -- this comment is not a mechanism." It then drifted a third
# time: every hand-written entry claimed 2026-08-03 while /pro and /privacy had
# taken content commits on 08-16 and six pages on 08-15, so crawlers were told
# that two weeks of edits to the money pages had not happened.
#
# This is that mechanism. lastmod comes from `git log -1 --format=%cs`, the
# committer date of the last commit that touched the file -- the same source
# publish-guide.py uses for the guide block, so the two halves of this file can
# no longer disagree about the same commit.
#
# WHAT IT DOES NOT TOUCH. The generated guide block between publish-guide.py's
# markers is left exactly as found: that block has an owner and this is not it.
# Priorities are read from the existing file and preserved, because they encode
# an editorial judgement about what matters, which git cannot know.
#
# A page that is deployed but missing here is added with a default priority; a
# page that no longer exists, or that firebase.json ignores, is removed. Pages
# robots.txt disallows are deliberately absent and stay absent.
import io
import os
import re
import subprocess
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SITEMAP = os.path.join(ROOT, 'site/sitemap.xml')
BASE = 'https://dagric.com'
DEFAULT_PRIORITY = '0.5'

# The guide block is regenerated by publish-guide.py; everything between these
# lines is off limits here.
GUIDE_MARK = re.compile(r'guide', re.I)


class GitUnavailable(Exception):
    """git itself could not be run — as distinct from git returning nothing."""


def sh(args):
    """Run a git command. Raises GitUnavailable if git cannot run at all.

    THE DISTINCTION MATTERS AND THIS USED TO SWALLOW IT. The old version caught
    every exception and returned '', so git_date() returned None, so main()
    skipped the entry -- and `--check` printed "all lastmod values match git"
    having compared nothing. Proven with a `git` stub returning 127 on PATH:
    exit 0, 23 entries, zero comparisons. A tree exported without .git, or a
    machine without git installed, got a green report from a check that had not
    run. That is this repo's own false-success bug class, in the tool written to
    replace a manual step precisely because manual steps drift.

    A command that runs and legitimately produces no output (a file with no
    commits yet) still returns '' -- that case is real and is handled by the
    caller. Only an inability to run git at all raises.
    """
    try:
        return subprocess.check_output(args, cwd=ROOT,
                                       stderr=subprocess.DEVNULL).decode().strip()
    except subprocess.CalledProcessError:
        # git ran and said no. Legitimate: an uncommitted file has no date.
        return ''
    except (OSError, FileNotFoundError) as e:
        raise GitUnavailable(str(e))


def git_date(relpath):
    """Committer date (YYYY-MM-DD) of the last commit touching relpath."""
    d = sh(['git', 'log', '-1', '--format=%cs', '--', relpath])
    return d or None


def ignored_patterns():
    import json
    with io.open(os.path.join(ROOT, 'firebase.json'), encoding='utf-8') as f:
        return json.load(f)['hosting'].get('ignore', [])


def disallowed():
    out = set()
    p = os.path.join(ROOT, 'site/robots.txt')
    if not os.path.exists(p):
        return out
    for line in io.open(p, encoding='utf-8'):
        m = re.match(r'\s*Disallow:\s*(/\S*)', line)
        if m:
            out.add(m.group(1).lstrip('/'))
    return out


def deployed_slugs():
    """Top-level pages Firebase will actually upload, as URL slugs."""
    import fnmatch
    ign = ignored_patterns()
    dis = disallowed()
    out = []
    site = os.path.join(ROOT, 'site')
    for name in sorted(os.listdir(site)):
        if not name.endswith('.html'):
            continue
        if any(fnmatch.fnmatch(name, p) for p in ign):
            continue
        slug = name[:-5]
        if slug == '404':
            continue
        if slug in dis:
            continue
        out.append(('' if slug == 'index' else slug, 'site/' + name))
    return out


URL_RE = re.compile(
    r'<url><loc>' + re.escape(BASE) + r'/(?P<slug>[^<]*)</loc>'
    r'<lastmod>(?P<date>[^<]*)</lastmod>'
    r'<priority>(?P<prio>[^<]*)</priority></url>')


def main():
    check = '--check' in sys.argv

    # Prove git works BEFORE reporting on anything it was supposed to tell us.
    # Without this the tool cannot distinguish "everything matches" from "I
    # could not look", and it reported the former for the latter.
    try:
        if not sh(['git', 'rev-parse', '--git-dir']):
            raise GitUnavailable('not a git repository')
    except GitUnavailable as e:
        print('sitemap: cannot run git (%s).' % e, file=sys.stderr)
        print('  lastmod values come from git and cannot be checked without it.',
              file=sys.stderr)
        return 2

    s = io.open(SITEMAP, encoding='utf-8', newline='').read()

    existing = {}
    for m in URL_RE.finditer(s):
        existing[m.group('slug').rstrip('/')] = (m.group('date'), m.group('prio'))

    changes = []
    out = s

    for slug, path in deployed_slugs():
        # The guide entries are generated; skip anything under guide/.
        if slug.startswith('guide'):
            continue
        newdate = git_date(path)
        if not newdate:
            # Never committed yet — leave today's file alone rather than
            # inventing a date. It will be picked up on the next run.
            if slug not in existing:
                changes.append('MISSING (uncommitted, not added yet): /%s' % slug)
            continue
        if slug in existing:
            olddate, prio = existing[slug]
            if olddate != newdate:
                changes.append('/%-18s %s -> %s' % (slug or '(home)', olddate, newdate))
                old = ('<url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                       '<priority>%s</priority></url>' % (BASE, slug, olddate, prio))
                new = ('<url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                       '<priority>%s</priority></url>' % (BASE, slug, newdate, prio))
                out = out.replace(old, new, 1)
        else:
            changes.append('/%-18s ADDED (%s)' % (slug, newdate))
            entry = ('  <url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                     '<priority>%s</priority></url>\n'
                     % (BASE, slug, newdate, DEFAULT_PRIORITY))
            out = out.replace('</urlset>', entry + '</urlset>', 1)

    # REMOVE ENTRIES THAT WILL 404, which this file's own docstring promised and
    # no code did. main() only ever updated what it found and appended what was
    # missing, so a page deleted from the tree -- or one firebase.json stops
    # uploading, which is exactly /family's situation -- stayed in the sitemap
    # advertising a URL that returns 404 to every crawler, while --check printed
    # "all lastmod values match git" and exited 0.
    #
    # A sitemap is a set of promises about what exists. Keeping a promise the
    # deploy no longer honours is worse than omitting it, because a 404 from a
    # sitemap URL is a quality signal search engines act on.
    live = set()
    for slug, _ in deployed_slugs():
        live.add(slug)
    for m in URL_RE.finditer(s):
        slug = m.group('slug').rstrip('/')
        if slug.startswith('guide') or slug == '':
            continue                      # generated block / the home page
        if slug in live:
            continue
        changes.append('/%-18s REMOVED (not deployed)' % slug)
        entry = m.group(0)
        # Take the whole line, including its indentation and newline.
        i = out.find(entry)
        if i >= 0:
            start = out.rfind('\n', 0, i) + 1
            end = out.find('\n', i) + 1
            out = out[:start] + out[end:]

    if not changes:
        print('sitemap: %d entries, all lastmod values match git, none stale' % len(existing))
        return 0

    for c in changes:
        print('  ' + c)
    if check:
        print('\nsitemap: DRIFT — run  python3 tools/sitemap.py  to correct it',
              file=sys.stderr)
        return 1
    io.open(SITEMAP, 'w', encoding='utf-8', newline='').write(out)
    print('\nsitemap: %d entr%s corrected' % (len(changes),
                                              'y' if len(changes) == 1 else 'ies'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
