#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 DGR Operations <repo@dagric.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Dagric OS -- keep site/sitemap.xml's hand-written entries honest.
#
#     python3 tools/sitemap.py           rewrite lastmod from git, add missing pages
#     python3 tools/sitemap.py --check   report drift and fail; change nothing
#
# WHY THIS EXISTS
# ---------------
# sitemap.xml's own header says it: "STILL A MANUAL STEP, AND THAT IS THE OPEN
# RISK... they have now drifted twice. The durable fix is to generate them from
# git the same way -- this comment is not a mechanism." It then drifted a third
# time: every hand-written entry claimed 2026-08-03 while /pro and /privacy had
# taken content commits on 08-16 and six pages on 08-15, so crawlers were told
# that two weeks of edits to the money pages had not happened.
#
# This is that mechanism. lastmod comes from `git log -1 --format=%cs`, the
# committer date of the last commit that touched the file -- the same source
# publish-guide.py uses for the guide block, so the two halves of this file can
# no longer disagree about the same commit.
#
# WHAT IT DOES NOT TOUCH. The generated guide block between publish-guide.py's
# markers is left exactly as found: that block has an owner and this is not it.
# Priorities are read from the existing file and preserved, because they encode
# an editorial judgement about what matters, which git cannot know.
#
# A page that is deployed but missing here is added with a default priority; a
# page that no longer exists, or that firebase.json ignores, is removed. Pages
# robots.txt disallows are deliberately absent and stay absent.
import io
import os
import re
import subprocess
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SITEMAP = os.path.join(ROOT, 'site/sitemap.xml')
BASE = 'https://dagric.com'
DEFAULT_PRIORITY = '0.5'

# The guide block is regenerated by publish-guide.py; everything between these
# lines is off limits here.
GUIDE_MARK = re.compile(r'guide', re.I)


def sh(args):
    try:
        return subprocess.check_output(args, cwd=ROOT,
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ''


def git_date(relpath):
    """Committer date (YYYY-MM-DD) of the last commit touching relpath."""
    d = sh(['git', 'log', '-1', '--format=%cs', '--', relpath])
    return d or None


def ignored_patterns():
    import json
    with io.open(os.path.join(ROOT, 'firebase.json'), encoding='utf-8') as f:
        return json.load(f)['hosting'].get('ignore', [])


def disallowed():
    out = set()
    p = os.path.join(ROOT, 'site/robots.txt')
    if not os.path.exists(p):
        return out
    for line in io.open(p, encoding='utf-8'):
        m = re.match(r'\s*Disallow:\s*(/\S*)', line)
        if m:
            out.add(m.group(1).lstrip('/'))
    return out


def deployed_slugs():
    """Top-level pages Firebase will actually upload, as URL slugs."""
    import fnmatch
    ign = ignored_patterns()
    dis = disallowed()
    out = []
    site = os.path.join(ROOT, 'site')
    for name in sorted(os.listdir(site)):
        if not name.endswith('.html'):
            continue
        if any(fnmatch.fnmatch(name, p) for p in ign):
            continue
        slug = name[:-5]
        if slug == '404':
            continue
        if slug in dis:
            continue
        out.append(('' if slug == 'index' else slug, 'site/' + name))
    return out


URL_RE = re.compile(
    r'<url><loc>' + re.escape(BASE) + r'/(?P<slug>[^<]*)</loc>'
    r'<lastmod>(?P<date>[^<]*)</lastmod>'
    r'<priority>(?P<prio>[^<]*)</priority></url>')


def main():
    check = '--check' in sys.argv
    s = io.open(SITEMAP, encoding='utf-8', newline='').read()

    existing = {}
    for m in URL_RE.finditer(s):
        existing[m.group('slug').rstrip('/')] = (m.group('date'), m.group('prio'))

    changes = []
    out = s

    for slug, path in deployed_slugs():
        # The guide entries are generated; skip anything under guide/.
        if slug.startswith('guide'):
            continue
        newdate = git_date(path)
        if not newdate:
            # Never committed yet — leave today's file alone rather than
            # inventing a date. It will be picked up on the next run.
            if slug not in existing:
                changes.append('MISSING (uncommitted, not added yet): /%s' % slug)
            continue
        if slug in existing:
            olddate, prio = existing[slug]
            if olddate != newdate:
                changes.append('/%-18s %s -> %s' % (slug or '(home)', olddate, newdate))
                old = ('<url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                       '<priority>%s</priority></url>' % (BASE, slug, olddate, prio))
                new = ('<url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                       '<priority>%s</priority></url>' % (BASE, slug, newdate, prio))
                out = out.replace(old, new, 1)
        else:
            changes.append('/%-18s ADDED (%s)' % (slug, newdate))
            entry = ('  <url><loc>%s/%s</loc><lastmod>%s</lastmod>'
                     '<priority>%s</priority></url>\n'
                     % (BASE, slug, newdate, DEFAULT_PRIORITY))
            out = out.replace('</urlset>', entry + '</urlset>', 1)

    if not changes:
        print('sitemap: %d entries, all lastmod values match git' % len(existing))
        return 0

    for c in changes:
        print('  ' + c)
    if check:
        print('\nsitemap: DRIFT — run  python3 tools/sitemap.py  to correct it',
              file=sys.stderr)
        return 1
    io.open(SITEMAP, 'w', encoding='utf-8', newline='').write(out)
    print('\nsitemap: %d entr%s corrected' % (len(changes),
                                              'y' if len(changes) == 1 else 'ies'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
